// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: steammessages_helprequest.steamworkssdk.proto
// Protobuf Java Version: 4.28.2

package com.nickbooher.protos.steamworks;

public final class SteamMsgHelpRequestSteamworks {
  private SteamMsgHelpRequestSteamworks() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      SteamMsgHelpRequestSteamworks.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CHelpRequestLogs_UploadUserApplicationLog_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dota2.CHelpRequestLogs_UploadUserApplicationLog_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 appid = 1;</code>
     * @return Whether the appid field is set.
     */
    boolean hasAppid();
    /**
     * <code>optional uint32 appid = 1;</code>
     * @return The appid.
     */
    int getAppid();

    /**
     * <code>optional string log_type = 2;</code>
     * @return Whether the logType field is set.
     */
    boolean hasLogType();
    /**
     * <code>optional string log_type = 2;</code>
     * @return The logType.
     */
    java.lang.String getLogType();
    /**
     * <code>optional string log_type = 2;</code>
     * @return The bytes for logType.
     */
    com.google.protobuf.ByteString
        getLogTypeBytes();

    /**
     * <code>optional string version_string = 3;</code>
     * @return Whether the versionString field is set.
     */
    boolean hasVersionString();
    /**
     * <code>optional string version_string = 3;</code>
     * @return The versionString.
     */
    java.lang.String getVersionString();
    /**
     * <code>optional string version_string = 3;</code>
     * @return The bytes for versionString.
     */
    com.google.protobuf.ByteString
        getVersionStringBytes();

    /**
     * <code>optional string log_contents = 4;</code>
     * @return Whether the logContents field is set.
     */
    boolean hasLogContents();
    /**
     * <code>optional string log_contents = 4;</code>
     * @return The logContents.
     */
    java.lang.String getLogContents();
    /**
     * <code>optional string log_contents = 4;</code>
     * @return The bytes for logContents.
     */
    com.google.protobuf.ByteString
        getLogContentsBytes();
  }
  /**
   * Protobuf type {@code dota2.CHelpRequestLogs_UploadUserApplicationLog_Request}
   */
  public static final class CHelpRequestLogs_UploadUserApplicationLog_Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dota2.CHelpRequestLogs_UploadUserApplicationLog_Request)
      CHelpRequestLogs_UploadUserApplicationLog_RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CHelpRequestLogs_UploadUserApplicationLog_Request.class.getName());
    }
    // Use CHelpRequestLogs_UploadUserApplicationLog_Request.newBuilder() to construct.
    private CHelpRequestLogs_UploadUserApplicationLog_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CHelpRequestLogs_UploadUserApplicationLog_Request() {
      logType_ = "";
      versionString_ = "";
      logContents_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request.class, com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request.Builder.class);
    }

    private int bitField0_;
    public static final int APPID_FIELD_NUMBER = 1;
    private int appid_ = 0;
    /**
     * <code>optional uint32 appid = 1;</code>
     * @return Whether the appid field is set.
     */
    @java.lang.Override
    public boolean hasAppid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 appid = 1;</code>
     * @return The appid.
     */
    @java.lang.Override
    public int getAppid() {
      return appid_;
    }

    public static final int LOG_TYPE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object logType_ = "";
    /**
     * <code>optional string log_type = 2;</code>
     * @return Whether the logType field is set.
     */
    @java.lang.Override
    public boolean hasLogType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string log_type = 2;</code>
     * @return The logType.
     */
    @java.lang.Override
    public java.lang.String getLogType() {
      java.lang.Object ref = logType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          logType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string log_type = 2;</code>
     * @return The bytes for logType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLogTypeBytes() {
      java.lang.Object ref = logType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_STRING_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object versionString_ = "";
    /**
     * <code>optional string version_string = 3;</code>
     * @return Whether the versionString field is set.
     */
    @java.lang.Override
    public boolean hasVersionString() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string version_string = 3;</code>
     * @return The versionString.
     */
    @java.lang.Override
    public java.lang.String getVersionString() {
      java.lang.Object ref = versionString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          versionString_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string version_string = 3;</code>
     * @return The bytes for versionString.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionStringBytes() {
      java.lang.Object ref = versionString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        versionString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOG_CONTENTS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object logContents_ = "";
    /**
     * <code>optional string log_contents = 4;</code>
     * @return Whether the logContents field is set.
     */
    @java.lang.Override
    public boolean hasLogContents() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string log_contents = 4;</code>
     * @return The logContents.
     */
    @java.lang.Override
    public java.lang.String getLogContents() {
      java.lang.Object ref = logContents_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          logContents_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string log_contents = 4;</code>
     * @return The bytes for logContents.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLogContentsBytes() {
      java.lang.Object ref = logContents_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logContents_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, appid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, logType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, versionString_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, logContents_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, appid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, logType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, versionString_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, logContents_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request other = (com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request) obj;

      if (hasAppid() != other.hasAppid()) return false;
      if (hasAppid()) {
        if (getAppid()
            != other.getAppid()) return false;
      }
      if (hasLogType() != other.hasLogType()) return false;
      if (hasLogType()) {
        if (!getLogType()
            .equals(other.getLogType())) return false;
      }
      if (hasVersionString() != other.hasVersionString()) return false;
      if (hasVersionString()) {
        if (!getVersionString()
            .equals(other.getVersionString())) return false;
      }
      if (hasLogContents() != other.hasLogContents()) return false;
      if (hasLogContents()) {
        if (!getLogContents()
            .equals(other.getLogContents())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAppid()) {
        hash = (37 * hash) + APPID_FIELD_NUMBER;
        hash = (53 * hash) + getAppid();
      }
      if (hasLogType()) {
        hash = (37 * hash) + LOG_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getLogType().hashCode();
      }
      if (hasVersionString()) {
        hash = (37 * hash) + VERSION_STRING_FIELD_NUMBER;
        hash = (53 * hash) + getVersionString().hashCode();
      }
      if (hasLogContents()) {
        hash = (37 * hash) + LOG_CONTENTS_FIELD_NUMBER;
        hash = (53 * hash) + getLogContents().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dota2.CHelpRequestLogs_UploadUserApplicationLog_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dota2.CHelpRequestLogs_UploadUserApplicationLog_Request)
        com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request.class, com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request.Builder.class);
      }

      // Construct using com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        appid_ = 0;
        logType_ = "";
        versionString_ = "";
        logContents_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Request_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request getDefaultInstanceForType() {
        return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request build() {
        com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request buildPartial() {
        com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request result = new com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.appid_ = appid_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.logType_ = logType_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.versionString_ = versionString_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.logContents_ = logContents_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request) {
          return mergeFrom((com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request other) {
        if (other == com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request.getDefaultInstance()) return this;
        if (other.hasAppid()) {
          setAppid(other.getAppid());
        }
        if (other.hasLogType()) {
          logType_ = other.logType_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasVersionString()) {
          versionString_ = other.versionString_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasLogContents()) {
          logContents_ = other.logContents_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                appid_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                logType_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                versionString_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                logContents_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int appid_ ;
      /**
       * <code>optional uint32 appid = 1;</code>
       * @return Whether the appid field is set.
       */
      @java.lang.Override
      public boolean hasAppid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 appid = 1;</code>
       * @return The appid.
       */
      @java.lang.Override
      public int getAppid() {
        return appid_;
      }
      /**
       * <code>optional uint32 appid = 1;</code>
       * @param value The appid to set.
       * @return This builder for chaining.
       */
      public Builder setAppid(int value) {

        appid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 appid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object logType_ = "";
      /**
       * <code>optional string log_type = 2;</code>
       * @return Whether the logType field is set.
       */
      public boolean hasLogType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string log_type = 2;</code>
       * @return The logType.
       */
      public java.lang.String getLogType() {
        java.lang.Object ref = logType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            logType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string log_type = 2;</code>
       * @return The bytes for logType.
       */
      public com.google.protobuf.ByteString
          getLogTypeBytes() {
        java.lang.Object ref = logType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string log_type = 2;</code>
       * @param value The logType to set.
       * @return This builder for chaining.
       */
      public Builder setLogType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        logType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string log_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogType() {
        logType_ = getDefaultInstance().getLogType();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string log_type = 2;</code>
       * @param value The bytes for logType to set.
       * @return This builder for chaining.
       */
      public Builder setLogTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        logType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object versionString_ = "";
      /**
       * <code>optional string version_string = 3;</code>
       * @return Whether the versionString field is set.
       */
      public boolean hasVersionString() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string version_string = 3;</code>
       * @return The versionString.
       */
      public java.lang.String getVersionString() {
        java.lang.Object ref = versionString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            versionString_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string version_string = 3;</code>
       * @return The bytes for versionString.
       */
      public com.google.protobuf.ByteString
          getVersionStringBytes() {
        java.lang.Object ref = versionString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          versionString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version_string = 3;</code>
       * @param value The versionString to set.
       * @return This builder for chaining.
       */
      public Builder setVersionString(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        versionString_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string version_string = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersionString() {
        versionString_ = getDefaultInstance().getVersionString();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string version_string = 3;</code>
       * @param value The bytes for versionString to set.
       * @return This builder for chaining.
       */
      public Builder setVersionStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        versionString_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object logContents_ = "";
      /**
       * <code>optional string log_contents = 4;</code>
       * @return Whether the logContents field is set.
       */
      public boolean hasLogContents() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string log_contents = 4;</code>
       * @return The logContents.
       */
      public java.lang.String getLogContents() {
        java.lang.Object ref = logContents_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            logContents_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string log_contents = 4;</code>
       * @return The bytes for logContents.
       */
      public com.google.protobuf.ByteString
          getLogContentsBytes() {
        java.lang.Object ref = logContents_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logContents_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string log_contents = 4;</code>
       * @param value The logContents to set.
       * @return This builder for chaining.
       */
      public Builder setLogContents(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        logContents_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string log_contents = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogContents() {
        logContents_ = getDefaultInstance().getLogContents();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string log_contents = 4;</code>
       * @param value The bytes for logContents to set.
       * @return This builder for chaining.
       */
      public Builder setLogContentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        logContents_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dota2.CHelpRequestLogs_UploadUserApplicationLog_Request)
    }

    // @@protoc_insertion_point(class_scope:dota2.CHelpRequestLogs_UploadUserApplicationLog_Request)
    private static final com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request();
    }

    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CHelpRequestLogs_UploadUserApplicationLog_Request>
        PARSER = new com.google.protobuf.AbstractParser<CHelpRequestLogs_UploadUserApplicationLog_Request>() {
      @java.lang.Override
      public CHelpRequestLogs_UploadUserApplicationLog_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CHelpRequestLogs_UploadUserApplicationLog_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CHelpRequestLogs_UploadUserApplicationLog_Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CHelpRequestLogs_UploadUserApplicationLog_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dota2.CHelpRequestLogs_UploadUserApplicationLog_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional uint64 id = 1;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * Protobuf type {@code dota2.CHelpRequestLogs_UploadUserApplicationLog_Response}
   */
  public static final class CHelpRequestLogs_UploadUserApplicationLog_Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dota2.CHelpRequestLogs_UploadUserApplicationLog_Response)
      CHelpRequestLogs_UploadUserApplicationLog_ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CHelpRequestLogs_UploadUserApplicationLog_Response.class.getName());
    }
    // Use CHelpRequestLogs_UploadUserApplicationLog_Response.newBuilder() to construct.
    private CHelpRequestLogs_UploadUserApplicationLog_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CHelpRequestLogs_UploadUserApplicationLog_Response() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response.class, com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>optional uint64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response other = (com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dota2.CHelpRequestLogs_UploadUserApplicationLog_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dota2.CHelpRequestLogs_UploadUserApplicationLog_Response)
        com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response.class, com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response.Builder.class);
      }

      // Construct using com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Response_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response getDefaultInstanceForType() {
        return com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response build() {
        com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response buildPartial() {
        com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response result = new com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response) {
          return mergeFrom((com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response other) {
        if (other == com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional uint64 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dota2.CHelpRequestLogs_UploadUserApplicationLog_Response)
    }

    // @@protoc_insertion_point(class_scope:dota2.CHelpRequestLogs_UploadUserApplicationLog_Response)
    private static final com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response();
    }

    public static com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CHelpRequestLogs_UploadUserApplicationLog_Response>
        PARSER = new com.google.protobuf.AbstractParser<CHelpRequestLogs_UploadUserApplicationLog_Response>() {
      @java.lang.Override
      public CHelpRequestLogs_UploadUserApplicationLog_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CHelpRequestLogs_UploadUserApplicationLog_Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CHelpRequestLogs_UploadUserApplicationLog_Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.steamworks.SteamMsgHelpRequestSteamworks.CHelpRequestLogs_UploadUserApplicationLog_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-steammessages_helprequest.steamworkssd" +
      "k.proto\022\005dota2\032.steammessages_unified_ba" +
      "se.steamworkssdk.proto\"\202\001\n1CHelpRequestL" +
      "ogs_UploadUserApplicationLog_Request\022\r\n\005" +
      "appid\030\001 \001(\r\022\020\n\010log_type\030\002 \001(\t\022\026\n\016version" +
      "_string\030\003 \001(\t\022\024\n\014log_contents\030\004 \001(\t\"@\n2C" +
      "HelpRequestLogs_UploadUserApplicationLog" +
      "_Response\022\n\n\002id\030\001 \001(\0042\372\001\n\017HelpRequestLog" +
      "s\022\264\001\n\030UploadUserApplicationLog\0228.dota2.C" +
      "HelpRequestLogs_UploadUserApplicationLog" +
      "_Request\0329.dota2.CHelpRequestLogs_Upload" +
      "UserApplicationLog_Response\"#\202\265\030\037User up" +
      "loading application logs\0320\202\265\030,Service fo" +
      "r dealing with user-submitted logsBD\n co" +
      "m.nickbooher.protos.steamworksB\035SteamMsg" +
      "HelpRequestSteamworks\200\001\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.nickbooher.protos.steamworks.SteamMsgUnifiedBaseSteamworks.getDescriptor(),
        });
    internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Request_descriptor,
        new java.lang.String[] { "Appid", "LogType", "VersionString", "LogContents", });
    internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dota2_CHelpRequestLogs_UploadUserApplicationLog_Response_descriptor,
        new java.lang.String[] { "Id", });
    descriptor.resolveAllFeaturesImmutable();
    com.nickbooher.protos.steamworks.SteamMsgUnifiedBaseSteamworks.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.nickbooher.protos.steamworks.SteamMsgUnifiedBaseSteamworks.methodDescription);
    registry.add(com.nickbooher.protos.steamworks.SteamMsgUnifiedBaseSteamworks.serviceDescription);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
