
package com.nickbooher.protos.steam.services;

import com.nickbooher.protos.steam.SteamMsgAccountHardware;

public interface IAccountHardware {

    public SteamMsgAccountHardware.CAccountHardware_RegisterSteamController_Response RegisterSteamController(SteamMsgAccountHardware.CAccountHardware_RegisterSteamController_Request request);

    public SteamMsgAccountHardware.CAccountHardware_CompleteSteamControllerRegistration_Response CompleteSteamControllerRegistration(SteamMsgAccountHardware.CAccountHardware_CompleteSteamControllerRegistration_Request request);

    public SteamMsgAccountHardware.CAccountHardware_QueryAccountsRegisteredToSerial_Response QueryAccountsRegisteredToController(SteamMsgAccountHardware.CAccountHardware_QueryAccountsRegisteredToSerial_Request request);

    public SteamMsgAccountHardware.CAccountHardware_SteamControllerSetConfig_Response SetDesiredControllerConfigForApp(SteamMsgAccountHardware.CAccountHardware_SteamControllerSetConfig_Request request);

    public SteamMsgAccountHardware.CAccountHardware_SteamControllerGetConfig_Response GetDesiredControllerConfigForApp(SteamMsgAccountHardware.CAccountHardware_SteamControllerGetConfig_Request request);

    public SteamMsgAccountHardware.CAccountHardware_DeRegisterSteamController_Response DeRegisterSteamController(SteamMsgAccountHardware.CAccountHardware_DeRegisterSteamController_Request request);

    public SteamMsgAccountHardware.CAccountHardware_SetPersonalizationFile_Response SetControllerPersonalizationFile(SteamMsgAccountHardware.CAccountHardware_SetPersonalizationFile_Request request);

    public SteamMsgAccountHardware.CAccountHardware_GetPersonalizationFile_Response GetControllerPersonalizationFile(SteamMsgAccountHardware.CAccountHardware_GetPersonalizationFile_Request request);

    public SteamMsgAccountHardware.CAccountHardware_VRCompatibilityCheck_Response VRCompatibilityCheck(SteamMsgAccountHardware.CAccountHardware_VRCompatibilityCheck_Request request);

    public SteamMsgAccountHardware.CAccountHardware_RegisterValveIndexComponent_Response RegisterValveIndexComponent(SteamMsgAccountHardware.CAccountHardware_RegisterValveIndexComponent_Request request);

    public SteamMsgAccountHardware.CAccountHardware_GetSteamDeckComponents_Response GetSteamDeckComponents(SteamMsgAccountHardware.CAccountHardware_GetSteamDeckComponents_Request request);
    
}

