
package com.nickbooher.protos.steam.services;

import com.nickbooher.protos.steam.SteamMsgFamilyGroups;

public interface IFamilyGroups {

    public SteamMsgFamilyGroups.CFamilyGroups_CreateFamilyGroup_Response CreateFamilyGroup(SteamMsgFamilyGroups.CFamilyGroups_CreateFamilyGroup_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_GetFamilyGroup_Response GetFamilyGroup(SteamMsgFamilyGroups.CFamilyGroups_GetFamilyGroup_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_GetFamilyGroupForUser_Response GetFamilyGroupForUser(SteamMsgFamilyGroups.CFamilyGroups_GetFamilyGroupForUser_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_ModifyFamilyGroupDetails_Response ModifyFamilyGroupDetails(SteamMsgFamilyGroups.CFamilyGroups_ModifyFamilyGroupDetails_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_InviteToFamilyGroup_Response InviteToFamilyGroup(SteamMsgFamilyGroups.CFamilyGroups_InviteToFamilyGroup_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_ConfirmInviteToFamilyGroup_Response ConfirmInviteToFamilyGroup(SteamMsgFamilyGroups.CFamilyGroups_ConfirmInviteToFamilyGroup_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_ResendInvitationToFamilyGroup_Response ResendInvitationToFamilyGroup(SteamMsgFamilyGroups.CFamilyGroups_ResendInvitationToFamilyGroup_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_JoinFamilyGroup_Response JoinFamilyGroup(SteamMsgFamilyGroups.CFamilyGroups_JoinFamilyGroup_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_ConfirmJoinFamilyGroup_Response ConfirmJoinFamilyGroup(SteamMsgFamilyGroups.CFamilyGroups_ConfirmJoinFamilyGroup_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_RemoveFromFamilyGroup_Response RemoveFromFamilyGroup(SteamMsgFamilyGroups.CFamilyGroups_RemoveFromFamilyGroup_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_CancelFamilyGroupInvite_Response CancelFamilyGroupInvite(SteamMsgFamilyGroups.CFamilyGroups_CancelFamilyGroupInvite_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_GetUsersSharingDevice_Response GetUsersSharingDevice(SteamMsgFamilyGroups.CFamilyGroups_GetUsersSharingDevice_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_DeleteFamilyGroup_Response DeleteFamilyGroup(SteamMsgFamilyGroups.CFamilyGroups_DeleteFamilyGroup_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_UndeleteFamilyGroup_Response UndeleteFamilyGroup(SteamMsgFamilyGroups.CFamilyGroups_UndeleteFamilyGroup_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_GetPlaytimeSummary_Response GetPlaytimeSummary(SteamMsgFamilyGroups.CFamilyGroups_GetPlaytimeSummary_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_RequestPurchase_Response RequestPurchase(SteamMsgFamilyGroups.CFamilyGroups_RequestPurchase_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_GetPurchaseRequests_Response GetPurchaseRequests(SteamMsgFamilyGroups.CFamilyGroups_GetPurchaseRequests_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_RespondToRequestedPurchase_Response RespondToRequestedPurchase(SteamMsgFamilyGroups.CFamilyGroups_RespondToRequestedPurchase_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_GetChangeLog_Response GetChangeLog(SteamMsgFamilyGroups.CFamilyGroups_GetChangeLog_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_SetFamilyCooldownOverrides_Response SetFamilyCooldownOverrides(SteamMsgFamilyGroups.CFamilyGroups_SetFamilyCooldownOverrides_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_GetSharedLibraryApps_Response GetSharedLibraryApps(SteamMsgFamilyGroups.CFamilyGroups_GetSharedLibraryApps_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_SetPreferredLender_Response SetPreferredLender(SteamMsgFamilyGroups.CFamilyGroups_SetPreferredLender_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_GetPreferredLenders_Response GetPreferredLenders(SteamMsgFamilyGroups.CFamilyGroups_GetPreferredLenders_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_ForceAcceptInvite_Response ForceAcceptInvite(SteamMsgFamilyGroups.CFamilyGroups_ForceAcceptInvite_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_GetInviteCheckResults_Response GetInviteCheckResults(SteamMsgFamilyGroups.CFamilyGroups_GetInviteCheckResults_Request request);

    public SteamMsgFamilyGroups.CFamilyGroups_ClearCooldownSkip_Response ClearCooldownSkip(SteamMsgFamilyGroups.CFamilyGroups_ClearCooldownSkip_Request request);
    
}

