// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service_sharedjscontext.proto
// Protobuf Java Version: 4.28.2

package com.nickbooher.protos.webui;

public final class SteamMsgSharedJSContext {
  private SteamMsgSharedJSContext() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      SteamMsgSharedJSContext.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CMsgSteamUIBrowserWindowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webui.CMsgSteamUIBrowserWindow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>optional int32 pid = 2;</code>
     * @return Whether the pid field is set.
     */
    boolean hasPid();
    /**
     * <code>optional int32 pid = 2;</code>
     * @return The pid.
     */
    int getPid();

    /**
     * <code>optional int32 browser_id = 3;</code>
     * @return Whether the browserId field is set.
     */
    boolean hasBrowserId();
    /**
     * <code>optional int32 browser_id = 3;</code>
     * @return The browserId.
     */
    int getBrowserId();

    /**
     * <code>optional int32 window_type = 4;</code>
     * @return Whether the windowType field is set.
     */
    boolean hasWindowType();
    /**
     * <code>optional int32 window_type = 4;</code>
     * @return The windowType.
     */
    int getWindowType();

    /**
     * <code>optional int32 x = 5;</code>
     * @return Whether the x field is set.
     */
    boolean hasX();
    /**
     * <code>optional int32 x = 5;</code>
     * @return The x.
     */
    int getX();

    /**
     * <code>optional int32 y = 6;</code>
     * @return Whether the y field is set.
     */
    boolean hasY();
    /**
     * <code>optional int32 y = 6;</code>
     * @return The y.
     */
    int getY();

    /**
     * <code>optional uint64 appid = 7;</code>
     * @return Whether the appid field is set.
     */
    boolean hasAppid();
    /**
     * <code>optional uint64 appid = 7;</code>
     * @return The appid.
     */
    long getAppid();

    /**
     * <code>optional uint64 parent_window_handle = 8;</code>
     * @return Whether the parentWindowHandle field is set.
     */
    boolean hasParentWindowHandle();
    /**
     * <code>optional uint64 parent_window_handle = 8;</code>
     * @return The parentWindowHandle.
     */
    long getParentWindowHandle();

    /**
     * <code>optional string app_name = 9;</code>
     * @return Whether the appName field is set.
     */
    boolean hasAppName();
    /**
     * <code>optional string app_name = 9;</code>
     * @return The appName.
     */
    java.lang.String getAppName();
    /**
     * <code>optional string app_name = 9;</code>
     * @return The bytes for appName.
     */
    com.google.protobuf.ByteString
        getAppNameBytes();

    /**
     * <code>optional bool gamepadui_via_gamescope = 10;</code>
     * @return Whether the gamepaduiViaGamescope field is set.
     */
    boolean hasGamepaduiViaGamescope();
    /**
     * <code>optional bool gamepadui_via_gamescope = 10;</code>
     * @return The gamepaduiViaGamescope.
     */
    boolean getGamepaduiViaGamescope();
  }
  /**
   * Protobuf type {@code webui.CMsgSteamUIBrowserWindow}
   */
  public static final class CMsgSteamUIBrowserWindow extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webui.CMsgSteamUIBrowserWindow)
      CMsgSteamUIBrowserWindowOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CMsgSteamUIBrowserWindow.class.getName());
    }
    // Use CMsgSteamUIBrowserWindow.newBuilder() to construct.
    private CMsgSteamUIBrowserWindow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CMsgSteamUIBrowserWindow() {
      appName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CMsgSteamUIBrowserWindow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CMsgSteamUIBrowserWindow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.class, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>optional int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int PID_FIELD_NUMBER = 2;
    private int pid_ = 0;
    /**
     * <code>optional int32 pid = 2;</code>
     * @return Whether the pid field is set.
     */
    @java.lang.Override
    public boolean hasPid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 pid = 2;</code>
     * @return The pid.
     */
    @java.lang.Override
    public int getPid() {
      return pid_;
    }

    public static final int BROWSER_ID_FIELD_NUMBER = 3;
    private int browserId_ = 0;
    /**
     * <code>optional int32 browser_id = 3;</code>
     * @return Whether the browserId field is set.
     */
    @java.lang.Override
    public boolean hasBrowserId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 browser_id = 3;</code>
     * @return The browserId.
     */
    @java.lang.Override
    public int getBrowserId() {
      return browserId_;
    }

    public static final int WINDOW_TYPE_FIELD_NUMBER = 4;
    private int windowType_ = 0;
    /**
     * <code>optional int32 window_type = 4;</code>
     * @return Whether the windowType field is set.
     */
    @java.lang.Override
    public boolean hasWindowType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 window_type = 4;</code>
     * @return The windowType.
     */
    @java.lang.Override
    public int getWindowType() {
      return windowType_;
    }

    public static final int X_FIELD_NUMBER = 5;
    private int x_ = 0;
    /**
     * <code>optional int32 x = 5;</code>
     * @return Whether the x field is set.
     */
    @java.lang.Override
    public boolean hasX() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 x = 5;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 6;
    private int y_ = 0;
    /**
     * <code>optional int32 y = 6;</code>
     * @return Whether the y field is set.
     */
    @java.lang.Override
    public boolean hasY() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 y = 6;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }

    public static final int APPID_FIELD_NUMBER = 7;
    private long appid_ = 0L;
    /**
     * <code>optional uint64 appid = 7;</code>
     * @return Whether the appid field is set.
     */
    @java.lang.Override
    public boolean hasAppid() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint64 appid = 7;</code>
     * @return The appid.
     */
    @java.lang.Override
    public long getAppid() {
      return appid_;
    }

    public static final int PARENT_WINDOW_HANDLE_FIELD_NUMBER = 8;
    private long parentWindowHandle_ = 0L;
    /**
     * <code>optional uint64 parent_window_handle = 8;</code>
     * @return Whether the parentWindowHandle field is set.
     */
    @java.lang.Override
    public boolean hasParentWindowHandle() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional uint64 parent_window_handle = 8;</code>
     * @return The parentWindowHandle.
     */
    @java.lang.Override
    public long getParentWindowHandle() {
      return parentWindowHandle_;
    }

    public static final int APP_NAME_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object appName_ = "";
    /**
     * <code>optional string app_name = 9;</code>
     * @return Whether the appName field is set.
     */
    @java.lang.Override
    public boolean hasAppName() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string app_name = 9;</code>
     * @return The appName.
     */
    @java.lang.Override
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string app_name = 9;</code>
     * @return The bytes for appName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GAMEPADUI_VIA_GAMESCOPE_FIELD_NUMBER = 10;
    private boolean gamepaduiViaGamescope_ = false;
    /**
     * <code>optional bool gamepadui_via_gamescope = 10;</code>
     * @return Whether the gamepaduiViaGamescope field is set.
     */
    @java.lang.Override
    public boolean hasGamepaduiViaGamescope() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional bool gamepadui_via_gamescope = 10;</code>
     * @return The gamepaduiViaGamescope.
     */
    @java.lang.Override
    public boolean getGamepaduiViaGamescope() {
      return gamepaduiViaGamescope_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, pid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, browserId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, windowType_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, x_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, y_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeUInt64(7, appid_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeUInt64(8, parentWindowHandle_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, appName_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeBool(10, gamepaduiViaGamescope_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, browserId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, windowType_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, x_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, y_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, appid_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, parentWindowHandle_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, appName_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, gamepaduiViaGamescope_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow other = (com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasPid() != other.hasPid()) return false;
      if (hasPid()) {
        if (getPid()
            != other.getPid()) return false;
      }
      if (hasBrowserId() != other.hasBrowserId()) return false;
      if (hasBrowserId()) {
        if (getBrowserId()
            != other.getBrowserId()) return false;
      }
      if (hasWindowType() != other.hasWindowType()) return false;
      if (hasWindowType()) {
        if (getWindowType()
            != other.getWindowType()) return false;
      }
      if (hasX() != other.hasX()) return false;
      if (hasX()) {
        if (getX()
            != other.getX()) return false;
      }
      if (hasY() != other.hasY()) return false;
      if (hasY()) {
        if (getY()
            != other.getY()) return false;
      }
      if (hasAppid() != other.hasAppid()) return false;
      if (hasAppid()) {
        if (getAppid()
            != other.getAppid()) return false;
      }
      if (hasParentWindowHandle() != other.hasParentWindowHandle()) return false;
      if (hasParentWindowHandle()) {
        if (getParentWindowHandle()
            != other.getParentWindowHandle()) return false;
      }
      if (hasAppName() != other.hasAppName()) return false;
      if (hasAppName()) {
        if (!getAppName()
            .equals(other.getAppName())) return false;
      }
      if (hasGamepaduiViaGamescope() != other.hasGamepaduiViaGamescope()) return false;
      if (hasGamepaduiViaGamescope()) {
        if (getGamepaduiViaGamescope()
            != other.getGamepaduiViaGamescope()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasPid()) {
        hash = (37 * hash) + PID_FIELD_NUMBER;
        hash = (53 * hash) + getPid();
      }
      if (hasBrowserId()) {
        hash = (37 * hash) + BROWSER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getBrowserId();
      }
      if (hasWindowType()) {
        hash = (37 * hash) + WINDOW_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getWindowType();
      }
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + getX();
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + getY();
      }
      if (hasAppid()) {
        hash = (37 * hash) + APPID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAppid());
      }
      if (hasParentWindowHandle()) {
        hash = (37 * hash) + PARENT_WINDOW_HANDLE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getParentWindowHandle());
      }
      if (hasAppName()) {
        hash = (37 * hash) + APP_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getAppName().hashCode();
      }
      if (hasGamepaduiViaGamescope()) {
        hash = (37 * hash) + GAMEPADUI_VIA_GAMESCOPE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getGamepaduiViaGamescope());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webui.CMsgSteamUIBrowserWindow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webui.CMsgSteamUIBrowserWindow)
        com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CMsgSteamUIBrowserWindow_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CMsgSteamUIBrowserWindow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.class, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder.class);
      }

      // Construct using com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        pid_ = 0;
        browserId_ = 0;
        windowType_ = 0;
        x_ = 0;
        y_ = 0;
        appid_ = 0L;
        parentWindowHandle_ = 0L;
        appName_ = "";
        gamepaduiViaGamescope_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CMsgSteamUIBrowserWindow_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow getDefaultInstanceForType() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow build() {
        com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow buildPartial() {
        com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow result = new com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pid_ = pid_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.browserId_ = browserId_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.windowType_ = windowType_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.x_ = x_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.y_ = y_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.appid_ = appid_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.parentWindowHandle_ = parentWindowHandle_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.appName_ = appName_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.gamepaduiViaGamescope_ = gamepaduiViaGamescope_;
          to_bitField0_ |= 0x00000200;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow) {
          return mergeFrom((com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow other) {
        if (other == com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasBrowserId()) {
          setBrowserId(other.getBrowserId());
        }
        if (other.hasWindowType()) {
          setWindowType(other.getWindowType());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasAppid()) {
          setAppid(other.getAppid());
        }
        if (other.hasParentWindowHandle()) {
          setParentWindowHandle(other.getParentWindowHandle());
        }
        if (other.hasAppName()) {
          appName_ = other.appName_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (other.hasGamepaduiViaGamescope()) {
          setGamepaduiViaGamescope(other.getGamepaduiViaGamescope());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                pid_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                browserId_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                windowType_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                x_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                y_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                appid_ = input.readUInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                parentWindowHandle_ = input.readUInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 74: {
                appName_ = input.readBytes();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 80: {
                gamepaduiViaGamescope_ = input.readBool();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>optional int32 pid = 2;</code>
       * @return Whether the pid field is set.
       */
      @java.lang.Override
      public boolean hasPid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 pid = 2;</code>
       * @return The pid.
       */
      @java.lang.Override
      public int getPid() {
        return pid_;
      }
      /**
       * <code>optional int32 pid = 2;</code>
       * @param value The pid to set.
       * @return This builder for chaining.
       */
      public Builder setPid(int value) {

        pid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        onChanged();
        return this;
      }

      private int browserId_ ;
      /**
       * <code>optional int32 browser_id = 3;</code>
       * @return Whether the browserId field is set.
       */
      @java.lang.Override
      public boolean hasBrowserId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 browser_id = 3;</code>
       * @return The browserId.
       */
      @java.lang.Override
      public int getBrowserId() {
        return browserId_;
      }
      /**
       * <code>optional int32 browser_id = 3;</code>
       * @param value The browserId to set.
       * @return This builder for chaining.
       */
      public Builder setBrowserId(int value) {

        browserId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 browser_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrowserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        browserId_ = 0;
        onChanged();
        return this;
      }

      private int windowType_ ;
      /**
       * <code>optional int32 window_type = 4;</code>
       * @return Whether the windowType field is set.
       */
      @java.lang.Override
      public boolean hasWindowType() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 window_type = 4;</code>
       * @return The windowType.
       */
      @java.lang.Override
      public int getWindowType() {
        return windowType_;
      }
      /**
       * <code>optional int32 window_type = 4;</code>
       * @param value The windowType to set.
       * @return This builder for chaining.
       */
      public Builder setWindowType(int value) {

        windowType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 window_type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWindowType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        windowType_ = 0;
        onChanged();
        return this;
      }

      private int x_ ;
      /**
       * <code>optional int32 x = 5;</code>
       * @return Whether the x field is set.
       */
      @java.lang.Override
      public boolean hasX() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 x = 5;</code>
       * @return The x.
       */
      @java.lang.Override
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 5;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(int value) {

        x_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000010);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>optional int32 y = 6;</code>
       * @return Whether the y field is set.
       */
      @java.lang.Override
      public boolean hasY() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 y = 6;</code>
       * @return The y.
       */
      @java.lang.Override
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 6;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(int value) {

        y_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000020);
        y_ = 0;
        onChanged();
        return this;
      }

      private long appid_ ;
      /**
       * <code>optional uint64 appid = 7;</code>
       * @return Whether the appid field is set.
       */
      @java.lang.Override
      public boolean hasAppid() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional uint64 appid = 7;</code>
       * @return The appid.
       */
      @java.lang.Override
      public long getAppid() {
        return appid_;
      }
      /**
       * <code>optional uint64 appid = 7;</code>
       * @param value The appid to set.
       * @return This builder for chaining.
       */
      public Builder setAppid(long value) {

        appid_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 appid = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppid() {
        bitField0_ = (bitField0_ & ~0x00000040);
        appid_ = 0L;
        onChanged();
        return this;
      }

      private long parentWindowHandle_ ;
      /**
       * <code>optional uint64 parent_window_handle = 8;</code>
       * @return Whether the parentWindowHandle field is set.
       */
      @java.lang.Override
      public boolean hasParentWindowHandle() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional uint64 parent_window_handle = 8;</code>
       * @return The parentWindowHandle.
       */
      @java.lang.Override
      public long getParentWindowHandle() {
        return parentWindowHandle_;
      }
      /**
       * <code>optional uint64 parent_window_handle = 8;</code>
       * @param value The parentWindowHandle to set.
       * @return This builder for chaining.
       */
      public Builder setParentWindowHandle(long value) {

        parentWindowHandle_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 parent_window_handle = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearParentWindowHandle() {
        bitField0_ = (bitField0_ & ~0x00000080);
        parentWindowHandle_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object appName_ = "";
      /**
       * <code>optional string app_name = 9;</code>
       * @return Whether the appName field is set.
       */
      public boolean hasAppName() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional string app_name = 9;</code>
       * @return The appName.
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string app_name = 9;</code>
       * @return The bytes for appName.
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string app_name = 9;</code>
       * @param value The appName to set.
       * @return This builder for chaining.
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        appName_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional string app_name = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppName() {
        appName_ = getDefaultInstance().getAppName();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>optional string app_name = 9;</code>
       * @param value The bytes for appName to set.
       * @return This builder for chaining.
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        appName_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private boolean gamepaduiViaGamescope_ ;
      /**
       * <code>optional bool gamepadui_via_gamescope = 10;</code>
       * @return Whether the gamepaduiViaGamescope field is set.
       */
      @java.lang.Override
      public boolean hasGamepaduiViaGamescope() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional bool gamepadui_via_gamescope = 10;</code>
       * @return The gamepaduiViaGamescope.
       */
      @java.lang.Override
      public boolean getGamepaduiViaGamescope() {
        return gamepaduiViaGamescope_;
      }
      /**
       * <code>optional bool gamepadui_via_gamescope = 10;</code>
       * @param value The gamepaduiViaGamescope to set.
       * @return This builder for chaining.
       */
      public Builder setGamepaduiViaGamescope(boolean value) {

        gamepaduiViaGamescope_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool gamepadui_via_gamescope = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearGamepaduiViaGamescope() {
        bitField0_ = (bitField0_ & ~0x00000200);
        gamepaduiViaGamescope_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:webui.CMsgSteamUIBrowserWindow)
    }

    // @@protoc_insertion_point(class_scope:webui.CMsgSteamUIBrowserWindow)
    private static final com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow();
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CMsgSteamUIBrowserWindow>
        PARSER = new com.google.protobuf.AbstractParser<CMsgSteamUIBrowserWindow>() {
      @java.lang.Override
      public CMsgSteamUIBrowserWindow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CMsgSteamUIBrowserWindow> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CMsgSteamUIBrowserWindow> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CSharedJSContext_GetDesiredSteamUIWindows_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webui.CSharedJSContext_GetDesiredSteamUIWindows_Request)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code webui.CSharedJSContext_GetDesiredSteamUIWindows_Request}
   */
  public static final class CSharedJSContext_GetDesiredSteamUIWindows_Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webui.CSharedJSContext_GetDesiredSteamUIWindows_Request)
      CSharedJSContext_GetDesiredSteamUIWindows_RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CSharedJSContext_GetDesiredSteamUIWindows_Request.class.getName());
    }
    // Use CSharedJSContext_GetDesiredSteamUIWindows_Request.newBuilder() to construct.
    private CSharedJSContext_GetDesiredSteamUIWindows_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CSharedJSContext_GetDesiredSteamUIWindows_Request() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request.class, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request other = (com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webui.CSharedJSContext_GetDesiredSteamUIWindows_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webui.CSharedJSContext_GetDesiredSteamUIWindows_Request)
        com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request.class, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request.Builder.class);
      }

      // Construct using com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Request_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request getDefaultInstanceForType() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request build() {
        com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request buildPartial() {
        com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request result = new com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request) {
          return mergeFrom((com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request other) {
        if (other == com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:webui.CSharedJSContext_GetDesiredSteamUIWindows_Request)
    }

    // @@protoc_insertion_point(class_scope:webui.CSharedJSContext_GetDesiredSteamUIWindows_Request)
    private static final com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request();
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CSharedJSContext_GetDesiredSteamUIWindows_Request>
        PARSER = new com.google.protobuf.AbstractParser<CSharedJSContext_GetDesiredSteamUIWindows_Request>() {
      @java.lang.Override
      public CSharedJSContext_GetDesiredSteamUIWindows_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CSharedJSContext_GetDesiredSteamUIWindows_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSharedJSContext_GetDesiredSteamUIWindows_Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CSharedJSContext_GetDesiredSteamUIWindows_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webui.CSharedJSContext_GetDesiredSteamUIWindows_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
     */
    java.util.List<com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow> 
        getWindowsList();
    /**
     * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
     */
    com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow getWindows(int index);
    /**
     * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
     */
    int getWindowsCount();
    /**
     * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
     */
    java.util.List<? extends com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindowOrBuilder> 
        getWindowsOrBuilderList();
    /**
     * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
     */
    com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindowOrBuilder getWindowsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code webui.CSharedJSContext_GetDesiredSteamUIWindows_Response}
   */
  public static final class CSharedJSContext_GetDesiredSteamUIWindows_Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webui.CSharedJSContext_GetDesiredSteamUIWindows_Response)
      CSharedJSContext_GetDesiredSteamUIWindows_ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CSharedJSContext_GetDesiredSteamUIWindows_Response.class.getName());
    }
    // Use CSharedJSContext_GetDesiredSteamUIWindows_Response.newBuilder() to construct.
    private CSharedJSContext_GetDesiredSteamUIWindows_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CSharedJSContext_GetDesiredSteamUIWindows_Response() {
      windows_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response.class, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response.Builder.class);
    }

    public static final int WINDOWS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow> windows_;
    /**
     * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow> getWindowsList() {
      return windows_;
    }
    /**
     * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindowOrBuilder> 
        getWindowsOrBuilderList() {
      return windows_;
    }
    /**
     * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
     */
    @java.lang.Override
    public int getWindowsCount() {
      return windows_.size();
    }
    /**
     * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
     */
    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow getWindows(int index) {
      return windows_.get(index);
    }
    /**
     * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
     */
    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindowOrBuilder getWindowsOrBuilder(
        int index) {
      return windows_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < windows_.size(); i++) {
        output.writeMessage(1, windows_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < windows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, windows_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response other = (com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response) obj;

      if (!getWindowsList()
          .equals(other.getWindowsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getWindowsCount() > 0) {
        hash = (37 * hash) + WINDOWS_FIELD_NUMBER;
        hash = (53 * hash) + getWindowsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webui.CSharedJSContext_GetDesiredSteamUIWindows_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webui.CSharedJSContext_GetDesiredSteamUIWindows_Response)
        com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response.class, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response.Builder.class);
      }

      // Construct using com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (windowsBuilder_ == null) {
          windows_ = java.util.Collections.emptyList();
        } else {
          windows_ = null;
          windowsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Response_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response getDefaultInstanceForType() {
        return com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response build() {
        com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response buildPartial() {
        com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response result = new com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response result) {
        if (windowsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            windows_ = java.util.Collections.unmodifiableList(windows_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.windows_ = windows_;
        } else {
          result.windows_ = windowsBuilder_.build();
        }
      }

      private void buildPartial0(com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response) {
          return mergeFrom((com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response other) {
        if (other == com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response.getDefaultInstance()) return this;
        if (windowsBuilder_ == null) {
          if (!other.windows_.isEmpty()) {
            if (windows_.isEmpty()) {
              windows_ = other.windows_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWindowsIsMutable();
              windows_.addAll(other.windows_);
            }
            onChanged();
          }
        } else {
          if (!other.windows_.isEmpty()) {
            if (windowsBuilder_.isEmpty()) {
              windowsBuilder_.dispose();
              windowsBuilder_ = null;
              windows_ = other.windows_;
              bitField0_ = (bitField0_ & ~0x00000001);
              windowsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWindowsFieldBuilder() : null;
            } else {
              windowsBuilder_.addAllMessages(other.windows_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow m =
                    input.readMessage(
                        com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.parser(),
                        extensionRegistry);
                if (windowsBuilder_ == null) {
                  ensureWindowsIsMutable();
                  windows_.add(m);
                } else {
                  windowsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow> windows_ =
        java.util.Collections.emptyList();
      private void ensureWindowsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          windows_ = new java.util.ArrayList<com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow>(windows_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindowOrBuilder> windowsBuilder_;

      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public java.util.List<com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow> getWindowsList() {
        if (windowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(windows_);
        } else {
          return windowsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public int getWindowsCount() {
        if (windowsBuilder_ == null) {
          return windows_.size();
        } else {
          return windowsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow getWindows(int index) {
        if (windowsBuilder_ == null) {
          return windows_.get(index);
        } else {
          return windowsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public Builder setWindows(
          int index, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow value) {
        if (windowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWindowsIsMutable();
          windows_.set(index, value);
          onChanged();
        } else {
          windowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public Builder setWindows(
          int index, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder builderForValue) {
        if (windowsBuilder_ == null) {
          ensureWindowsIsMutable();
          windows_.set(index, builderForValue.build());
          onChanged();
        } else {
          windowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public Builder addWindows(com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow value) {
        if (windowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWindowsIsMutable();
          windows_.add(value);
          onChanged();
        } else {
          windowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public Builder addWindows(
          int index, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow value) {
        if (windowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWindowsIsMutable();
          windows_.add(index, value);
          onChanged();
        } else {
          windowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public Builder addWindows(
          com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder builderForValue) {
        if (windowsBuilder_ == null) {
          ensureWindowsIsMutable();
          windows_.add(builderForValue.build());
          onChanged();
        } else {
          windowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public Builder addWindows(
          int index, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder builderForValue) {
        if (windowsBuilder_ == null) {
          ensureWindowsIsMutable();
          windows_.add(index, builderForValue.build());
          onChanged();
        } else {
          windowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public Builder addAllWindows(
          java.lang.Iterable<? extends com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow> values) {
        if (windowsBuilder_ == null) {
          ensureWindowsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, windows_);
          onChanged();
        } else {
          windowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public Builder clearWindows() {
        if (windowsBuilder_ == null) {
          windows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          windowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public Builder removeWindows(int index) {
        if (windowsBuilder_ == null) {
          ensureWindowsIsMutable();
          windows_.remove(index);
          onChanged();
        } else {
          windowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder getWindowsBuilder(
          int index) {
        return getWindowsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindowOrBuilder getWindowsOrBuilder(
          int index) {
        if (windowsBuilder_ == null) {
          return windows_.get(index);  } else {
          return windowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public java.util.List<? extends com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindowOrBuilder> 
           getWindowsOrBuilderList() {
        if (windowsBuilder_ != null) {
          return windowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(windows_);
        }
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder addWindowsBuilder() {
        return getWindowsFieldBuilder().addBuilder(
            com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.getDefaultInstance());
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder addWindowsBuilder(
          int index) {
        return getWindowsFieldBuilder().addBuilder(
            index, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.getDefaultInstance());
      }
      /**
       * <code>repeated .webui.CMsgSteamUIBrowserWindow windows = 1;</code>
       */
      public java.util.List<com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder> 
           getWindowsBuilderList() {
        return getWindowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindowOrBuilder> 
          getWindowsFieldBuilder() {
        if (windowsBuilder_ == null) {
          windowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindow.Builder, com.nickbooher.protos.webui.SteamMsgSharedJSContext.CMsgSteamUIBrowserWindowOrBuilder>(
                  windows_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          windows_ = null;
        }
        return windowsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:webui.CSharedJSContext_GetDesiredSteamUIWindows_Response)
    }

    // @@protoc_insertion_point(class_scope:webui.CSharedJSContext_GetDesiredSteamUIWindows_Response)
    private static final com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response();
    }

    public static com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CSharedJSContext_GetDesiredSteamUIWindows_Response>
        PARSER = new com.google.protobuf.AbstractParser<CSharedJSContext_GetDesiredSteamUIWindows_Response>() {
      @java.lang.Override
      public CSharedJSContext_GetDesiredSteamUIWindows_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CSharedJSContext_GetDesiredSteamUIWindows_Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSharedJSContext_GetDesiredSteamUIWindows_Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgSharedJSContext.CSharedJSContext_GetDesiredSteamUIWindows_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webui_CMsgSteamUIBrowserWindow_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webui_CMsgSteamUIBrowserWindow_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035service_sharedjscontext.proto\022\005webui\"\322" +
      "\001\n\030CMsgSteamUIBrowserWindow\022\n\n\002id\030\001 \001(\005\022" +
      "\013\n\003pid\030\002 \001(\005\022\022\n\nbrowser_id\030\003 \001(\005\022\023\n\013wind" +
      "ow_type\030\004 \001(\005\022\t\n\001x\030\005 \001(\005\022\t\n\001y\030\006 \001(\005\022\r\n\005a" +
      "ppid\030\007 \001(\004\022\034\n\024parent_window_handle\030\010 \001(\004" +
      "\022\020\n\010app_name\030\t \001(\t\022\037\n\027gamepadui_via_game" +
      "scope\030\n \001(\010\"3\n1CSharedJSContext_GetDesir" +
      "edSteamUIWindows_Request\"f\n2CSharedJSCon" +
      "text_GetDesiredSteamUIWindows_Response\0220" +
      "\n\007windows\030\001 \003(\0132\037.webui.CMsgSteamUIBrows" +
      "erWindow2\243\001\n\017SharedJSContext\022\217\001\n\030GetDesi" +
      "redSteamUIWindows\0228.webui.CSharedJSConte" +
      "xt_GetDesiredSteamUIWindows_Request\0329.we" +
      "bui.CSharedJSContext_GetDesiredSteamUIWi" +
      "ndows_ResponseB6\n\033com.nickbooher.protos." +
      "webuiB\027SteamMsgSharedJSContext"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_webui_CMsgSteamUIBrowserWindow_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webui_CMsgSteamUIBrowserWindow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webui_CMsgSteamUIBrowserWindow_descriptor,
        new java.lang.String[] { "Id", "Pid", "BrowserId", "WindowType", "X", "Y", "Appid", "ParentWindowHandle", "AppName", "GamepaduiViaGamescope", });
    internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Request_descriptor,
        new java.lang.String[] { });
    internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webui_CSharedJSContext_GetDesiredSteamUIWindows_Response_descriptor,
        new java.lang.String[] { "Windows", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
