// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service_experimentservice.proto
// Protobuf Java Version: 4.28.2

package com.nickbooher.protos.webui;

public final class SteamMsgExperimentService {
  private SteamMsgExperimentService() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      SteamMsgExperimentService.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037service_experimentservice.proto\022\005webui" +
      "\032\021common_base.proto2c\n\021ExperimentService" +
      "\022N\n\"ReportProductImpressionsFromClient\022\025" +
      ".webui.NotImplemented\032\021.webui.NoResponse" +
      "B8\n\033com.nickbooher.protos.webuiB\031SteamMs" +
      "gExperimentService"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.nickbooher.protos.webui.SteamMsgCommonBase.getDescriptor(),
        });
    descriptor.resolveAllFeaturesImmutable();
    com.nickbooher.protos.webui.SteamMsgCommonBase.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
