// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service_wishlist.proto
// Protobuf Java Version: 4.28.2

package com.nickbooher.protos.webui;

public final class SteamMsgWishlist {
  private SteamMsgWishlist() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      SteamMsgWishlist.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CWishlist_GetWishlistItemsOnSale_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webui.CWishlist_GetWishlistItemsOnSale_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .webui.StoreBrowseContext context = 1;</code>
     * @return Whether the context field is set.
     */
    boolean hasContext();
    /**
     * <code>optional .webui.StoreBrowseContext context = 1;</code>
     * @return The context.
     */
    com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext getContext();
    /**
     * <code>optional .webui.StoreBrowseContext context = 1;</code>
     */
    com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContextOrBuilder getContextOrBuilder();

    /**
     * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
     * @return Whether the dataRequest field is set.
     */
    boolean hasDataRequest();
    /**
     * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
     * @return The dataRequest.
     */
    com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest getDataRequest();
    /**
     * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
     */
    com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequestOrBuilder getDataRequestOrBuilder();
  }
  /**
   * Protobuf type {@code webui.CWishlist_GetWishlistItemsOnSale_Request}
   */
  public static final class CWishlist_GetWishlistItemsOnSale_Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webui.CWishlist_GetWishlistItemsOnSale_Request)
      CWishlist_GetWishlistItemsOnSale_RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CWishlist_GetWishlistItemsOnSale_Request.class.getName());
    }
    // Use CWishlist_GetWishlistItemsOnSale_Request.newBuilder() to construct.
    private CWishlist_GetWishlistItemsOnSale_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CWishlist_GetWishlistItemsOnSale_Request() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request.class, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request.Builder.class);
    }

    private int bitField0_;
    public static final int CONTEXT_FIELD_NUMBER = 1;
    private com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext context_;
    /**
     * <code>optional .webui.StoreBrowseContext context = 1;</code>
     * @return Whether the context field is set.
     */
    @java.lang.Override
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .webui.StoreBrowseContext context = 1;</code>
     * @return The context.
     */
    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext getContext() {
      return context_ == null ? com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext.getDefaultInstance() : context_;
    }
    /**
     * <code>optional .webui.StoreBrowseContext context = 1;</code>
     */
    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContextOrBuilder getContextOrBuilder() {
      return context_ == null ? com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext.getDefaultInstance() : context_;
    }

    public static final int DATA_REQUEST_FIELD_NUMBER = 2;
    private com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest dataRequest_;
    /**
     * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
     * @return Whether the dataRequest field is set.
     */
    @java.lang.Override
    public boolean hasDataRequest() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
     * @return The dataRequest.
     */
    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest getDataRequest() {
      return dataRequest_ == null ? com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest.getDefaultInstance() : dataRequest_;
    }
    /**
     * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
     */
    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequestOrBuilder getDataRequestOrBuilder() {
      return dataRequest_ == null ? com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest.getDefaultInstance() : dataRequest_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getContext());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getDataRequest());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getContext());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDataRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request other = (com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request) obj;

      if (hasContext() != other.hasContext()) return false;
      if (hasContext()) {
        if (!getContext()
            .equals(other.getContext())) return false;
      }
      if (hasDataRequest() != other.hasDataRequest()) return false;
      if (hasDataRequest()) {
        if (!getDataRequest()
            .equals(other.getDataRequest())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasContext()) {
        hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getContext().hashCode();
      }
      if (hasDataRequest()) {
        hash = (37 * hash) + DATA_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getDataRequest().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webui.CWishlist_GetWishlistItemsOnSale_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webui.CWishlist_GetWishlistItemsOnSale_Request)
        com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request.class, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request.Builder.class);
      }

      // Construct using com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getContextFieldBuilder();
          getDataRequestFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        context_ = null;
        if (contextBuilder_ != null) {
          contextBuilder_.dispose();
          contextBuilder_ = null;
        }
        dataRequest_ = null;
        if (dataRequestBuilder_ != null) {
          dataRequestBuilder_.dispose();
          dataRequestBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Request_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request getDefaultInstanceForType() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request build() {
        com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request buildPartial() {
        com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request result = new com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.context_ = contextBuilder_ == null
              ? context_
              : contextBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dataRequest_ = dataRequestBuilder_ == null
              ? dataRequest_
              : dataRequestBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request) {
          return mergeFrom((com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request other) {
        if (other == com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request.getDefaultInstance()) return this;
        if (other.hasContext()) {
          mergeContext(other.getContext());
        }
        if (other.hasDataRequest()) {
          mergeDataRequest(other.getDataRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getContextFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getDataRequestFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext context_;
      private com.google.protobuf.SingleFieldBuilder<
          com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext.Builder, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContextOrBuilder> contextBuilder_;
      /**
       * <code>optional .webui.StoreBrowseContext context = 1;</code>
       * @return Whether the context field is set.
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .webui.StoreBrowseContext context = 1;</code>
       * @return The context.
       */
      public com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext getContext() {
        if (contextBuilder_ == null) {
          return context_ == null ? com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext.getDefaultInstance() : context_;
        } else {
          return contextBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .webui.StoreBrowseContext context = 1;</code>
       */
      public Builder setContext(com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext value) {
        if (contextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          context_ = value;
        } else {
          contextBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .webui.StoreBrowseContext context = 1;</code>
       */
      public Builder setContext(
          com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext.Builder builderForValue) {
        if (contextBuilder_ == null) {
          context_ = builderForValue.build();
        } else {
          contextBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .webui.StoreBrowseContext context = 1;</code>
       */
      public Builder mergeContext(com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext value) {
        if (contextBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            context_ != null &&
            context_ != com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext.getDefaultInstance()) {
            getContextBuilder().mergeFrom(value);
          } else {
            context_ = value;
          }
        } else {
          contextBuilder_.mergeFrom(value);
        }
        if (context_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .webui.StoreBrowseContext context = 1;</code>
       */
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000001);
        context_ = null;
        if (contextBuilder_ != null) {
          contextBuilder_.dispose();
          contextBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .webui.StoreBrowseContext context = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext.Builder getContextBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getContextFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .webui.StoreBrowseContext context = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContextOrBuilder getContextOrBuilder() {
        if (contextBuilder_ != null) {
          return contextBuilder_.getMessageOrBuilder();
        } else {
          return context_ == null ?
              com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext.getDefaultInstance() : context_;
        }
      }
      /**
       * <code>optional .webui.StoreBrowseContext context = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext.Builder, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContextOrBuilder> 
          getContextFieldBuilder() {
        if (contextBuilder_ == null) {
          contextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContext.Builder, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseContextOrBuilder>(
                  getContext(),
                  getParentForChildren(),
                  isClean());
          context_ = null;
        }
        return contextBuilder_;
      }

      private com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest dataRequest_;
      private com.google.protobuf.SingleFieldBuilder<
          com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest.Builder, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequestOrBuilder> dataRequestBuilder_;
      /**
       * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
       * @return Whether the dataRequest field is set.
       */
      public boolean hasDataRequest() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
       * @return The dataRequest.
       */
      public com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest getDataRequest() {
        if (dataRequestBuilder_ == null) {
          return dataRequest_ == null ? com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest.getDefaultInstance() : dataRequest_;
        } else {
          return dataRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
       */
      public Builder setDataRequest(com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest value) {
        if (dataRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataRequest_ = value;
        } else {
          dataRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
       */
      public Builder setDataRequest(
          com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest.Builder builderForValue) {
        if (dataRequestBuilder_ == null) {
          dataRequest_ = builderForValue.build();
        } else {
          dataRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
       */
      public Builder mergeDataRequest(com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest value) {
        if (dataRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            dataRequest_ != null &&
            dataRequest_ != com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest.getDefaultInstance()) {
            getDataRequestBuilder().mergeFrom(value);
          } else {
            dataRequest_ = value;
          }
        } else {
          dataRequestBuilder_.mergeFrom(value);
        }
        if (dataRequest_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
       */
      public Builder clearDataRequest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dataRequest_ = null;
        if (dataRequestBuilder_ != null) {
          dataRequestBuilder_.dispose();
          dataRequestBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest.Builder getDataRequestBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDataRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequestOrBuilder getDataRequestOrBuilder() {
        if (dataRequestBuilder_ != null) {
          return dataRequestBuilder_.getMessageOrBuilder();
        } else {
          return dataRequest_ == null ?
              com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest.getDefaultInstance() : dataRequest_;
        }
      }
      /**
       * <code>optional .webui.StoreBrowseItemDataRequest data_request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest.Builder, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequestOrBuilder> 
          getDataRequestFieldBuilder() {
        if (dataRequestBuilder_ == null) {
          dataRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequest.Builder, com.nickbooher.protos.webui.SteamMsgCommon.StoreBrowseItemDataRequestOrBuilder>(
                  getDataRequest(),
                  getParentForChildren(),
                  isClean());
          dataRequest_ = null;
        }
        return dataRequestBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:webui.CWishlist_GetWishlistItemsOnSale_Request)
    }

    // @@protoc_insertion_point(class_scope:webui.CWishlist_GetWishlistItemsOnSale_Request)
    private static final com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request();
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CWishlist_GetWishlistItemsOnSale_Request>
        PARSER = new com.google.protobuf.AbstractParser<CWishlist_GetWishlistItemsOnSale_Request>() {
      @java.lang.Override
      public CWishlist_GetWishlistItemsOnSale_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CWishlist_GetWishlistItemsOnSale_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CWishlist_GetWishlistItemsOnSale_Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CWishlist_GetWishlistItemsOnSale_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webui.CWishlist_GetWishlistItemsOnSale_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
     */
    java.util.List<com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem> 
        getItemsList();
    /**
     * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
     */
    com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem getItems(int index);
    /**
     * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
     */
    java.util.List<? extends com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
     */
    com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code webui.CWishlist_GetWishlistItemsOnSale_Response}
   */
  public static final class CWishlist_GetWishlistItemsOnSale_Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webui.CWishlist_GetWishlistItemsOnSale_Response)
      CWishlist_GetWishlistItemsOnSale_ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CWishlist_GetWishlistItemsOnSale_Response.class.getName());
    }
    // Use CWishlist_GetWishlistItemsOnSale_Response.newBuilder() to construct.
    private CWishlist_GetWishlistItemsOnSale_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CWishlist_GetWishlistItemsOnSale_Response() {
      items_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response.class, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem> items_;
    /**
     * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
     */
    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
     */
    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response other = (com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webui.CWishlist_GetWishlistItemsOnSale_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webui.CWishlist_GetWishlistItemsOnSale_Response)
        com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response.class, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response.Builder.class);
      }

      // Construct using com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
        } else {
          items_ = null;
          itemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response getDefaultInstanceForType() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response build() {
        com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response buildPartial() {
        com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response result = new com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response result) {
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
      }

      private void buildPartial0(com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response) {
          return mergeFrom((com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response other) {
        if (other == com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem m =
                    input.readMessage(
                        com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.parser(),
                        extensionRegistry);
                if (itemsBuilder_ == null) {
                  ensureItemsIsMutable();
                  items_.add(m);
                } else {
                  itemsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public java.util.List<com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public Builder setItems(
          int index, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public Builder setItems(
          int index, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public Builder addItems(com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public Builder addItems(
          int index, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public Builder addItems(
          com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public Builder addItems(
          int index, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public java.util.List<? extends com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.getDefaultInstance());
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.getDefaultInstance());
      }
      /**
       * <code>repeated .webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem items = 1;</code>
       */
      public java.util.List<com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:webui.CWishlist_GetWishlistItemsOnSale_Response)
    }

    // @@protoc_insertion_point(class_scope:webui.CWishlist_GetWishlistItemsOnSale_Response)
    private static final com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response();
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CWishlist_GetWishlistItemsOnSale_Response>
        PARSER = new com.google.protobuf.AbstractParser<CWishlist_GetWishlistItemsOnSale_Response>() {
      @java.lang.Override
      public CWishlist_GetWishlistItemsOnSale_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CWishlist_GetWishlistItemsOnSale_Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CWishlist_GetWishlistItemsOnSale_Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 appid = 1;</code>
     * @return Whether the appid field is set.
     */
    boolean hasAppid();
    /**
     * <code>optional uint32 appid = 1;</code>
     * @return The appid.
     */
    int getAppid();

    /**
     * <code>optional .webui.StoreItem store_item = 2;</code>
     * @return Whether the storeItem field is set.
     */
    boolean hasStoreItem();
    /**
     * <code>optional .webui.StoreItem store_item = 2;</code>
     * @return The storeItem.
     */
    com.nickbooher.protos.webui.SteamMsgCommon.StoreItem getStoreItem();
    /**
     * <code>optional .webui.StoreItem store_item = 2;</code>
     */
    com.nickbooher.protos.webui.SteamMsgCommon.StoreItemOrBuilder getStoreItemOrBuilder();
  }
  /**
   * Protobuf type {@code webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem}
   */
  public static final class CWishlist_GetWishlistItemsOnSale_Response_WishlistItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem)
      CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.class.getName());
    }
    // Use CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.newBuilder() to construct.
    private CWishlist_GetWishlistItemsOnSale_Response_WishlistItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CWishlist_GetWishlistItemsOnSale_Response_WishlistItem() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_WishlistItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_WishlistItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.class, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder.class);
    }

    private int bitField0_;
    public static final int APPID_FIELD_NUMBER = 1;
    private int appid_ = 0;
    /**
     * <code>optional uint32 appid = 1;</code>
     * @return Whether the appid field is set.
     */
    @java.lang.Override
    public boolean hasAppid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 appid = 1;</code>
     * @return The appid.
     */
    @java.lang.Override
    public int getAppid() {
      return appid_;
    }

    public static final int STORE_ITEM_FIELD_NUMBER = 2;
    private com.nickbooher.protos.webui.SteamMsgCommon.StoreItem storeItem_;
    /**
     * <code>optional .webui.StoreItem store_item = 2;</code>
     * @return Whether the storeItem field is set.
     */
    @java.lang.Override
    public boolean hasStoreItem() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .webui.StoreItem store_item = 2;</code>
     * @return The storeItem.
     */
    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgCommon.StoreItem getStoreItem() {
      return storeItem_ == null ? com.nickbooher.protos.webui.SteamMsgCommon.StoreItem.getDefaultInstance() : storeItem_;
    }
    /**
     * <code>optional .webui.StoreItem store_item = 2;</code>
     */
    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgCommon.StoreItemOrBuilder getStoreItemOrBuilder() {
      return storeItem_ == null ? com.nickbooher.protos.webui.SteamMsgCommon.StoreItem.getDefaultInstance() : storeItem_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, appid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getStoreItem());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, appid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStoreItem());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem other = (com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem) obj;

      if (hasAppid() != other.hasAppid()) return false;
      if (hasAppid()) {
        if (getAppid()
            != other.getAppid()) return false;
      }
      if (hasStoreItem() != other.hasStoreItem()) return false;
      if (hasStoreItem()) {
        if (!getStoreItem()
            .equals(other.getStoreItem())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAppid()) {
        hash = (37 * hash) + APPID_FIELD_NUMBER;
        hash = (53 * hash) + getAppid();
      }
      if (hasStoreItem()) {
        hash = (37 * hash) + STORE_ITEM_FIELD_NUMBER;
        hash = (53 * hash) + getStoreItem().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem)
        com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_WishlistItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_WishlistItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.class, com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.Builder.class);
      }

      // Construct using com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getStoreItemFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        appid_ = 0;
        storeItem_ = null;
        if (storeItemBuilder_ != null) {
          storeItemBuilder_.dispose();
          storeItemBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_WishlistItem_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem getDefaultInstanceForType() {
        return com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem build() {
        com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem buildPartial() {
        com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem result = new com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.appid_ = appid_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.storeItem_ = storeItemBuilder_ == null
              ? storeItem_
              : storeItemBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem) {
          return mergeFrom((com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem other) {
        if (other == com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem.getDefaultInstance()) return this;
        if (other.hasAppid()) {
          setAppid(other.getAppid());
        }
        if (other.hasStoreItem()) {
          mergeStoreItem(other.getStoreItem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                appid_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getStoreItemFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int appid_ ;
      /**
       * <code>optional uint32 appid = 1;</code>
       * @return Whether the appid field is set.
       */
      @java.lang.Override
      public boolean hasAppid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 appid = 1;</code>
       * @return The appid.
       */
      @java.lang.Override
      public int getAppid() {
        return appid_;
      }
      /**
       * <code>optional uint32 appid = 1;</code>
       * @param value The appid to set.
       * @return This builder for chaining.
       */
      public Builder setAppid(int value) {

        appid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 appid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appid_ = 0;
        onChanged();
        return this;
      }

      private com.nickbooher.protos.webui.SteamMsgCommon.StoreItem storeItem_;
      private com.google.protobuf.SingleFieldBuilder<
          com.nickbooher.protos.webui.SteamMsgCommon.StoreItem, com.nickbooher.protos.webui.SteamMsgCommon.StoreItem.Builder, com.nickbooher.protos.webui.SteamMsgCommon.StoreItemOrBuilder> storeItemBuilder_;
      /**
       * <code>optional .webui.StoreItem store_item = 2;</code>
       * @return Whether the storeItem field is set.
       */
      public boolean hasStoreItem() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .webui.StoreItem store_item = 2;</code>
       * @return The storeItem.
       */
      public com.nickbooher.protos.webui.SteamMsgCommon.StoreItem getStoreItem() {
        if (storeItemBuilder_ == null) {
          return storeItem_ == null ? com.nickbooher.protos.webui.SteamMsgCommon.StoreItem.getDefaultInstance() : storeItem_;
        } else {
          return storeItemBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .webui.StoreItem store_item = 2;</code>
       */
      public Builder setStoreItem(com.nickbooher.protos.webui.SteamMsgCommon.StoreItem value) {
        if (storeItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          storeItem_ = value;
        } else {
          storeItemBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .webui.StoreItem store_item = 2;</code>
       */
      public Builder setStoreItem(
          com.nickbooher.protos.webui.SteamMsgCommon.StoreItem.Builder builderForValue) {
        if (storeItemBuilder_ == null) {
          storeItem_ = builderForValue.build();
        } else {
          storeItemBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .webui.StoreItem store_item = 2;</code>
       */
      public Builder mergeStoreItem(com.nickbooher.protos.webui.SteamMsgCommon.StoreItem value) {
        if (storeItemBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            storeItem_ != null &&
            storeItem_ != com.nickbooher.protos.webui.SteamMsgCommon.StoreItem.getDefaultInstance()) {
            getStoreItemBuilder().mergeFrom(value);
          } else {
            storeItem_ = value;
          }
        } else {
          storeItemBuilder_.mergeFrom(value);
        }
        if (storeItem_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .webui.StoreItem store_item = 2;</code>
       */
      public Builder clearStoreItem() {
        bitField0_ = (bitField0_ & ~0x00000002);
        storeItem_ = null;
        if (storeItemBuilder_ != null) {
          storeItemBuilder_.dispose();
          storeItemBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .webui.StoreItem store_item = 2;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgCommon.StoreItem.Builder getStoreItemBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getStoreItemFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .webui.StoreItem store_item = 2;</code>
       */
      public com.nickbooher.protos.webui.SteamMsgCommon.StoreItemOrBuilder getStoreItemOrBuilder() {
        if (storeItemBuilder_ != null) {
          return storeItemBuilder_.getMessageOrBuilder();
        } else {
          return storeItem_ == null ?
              com.nickbooher.protos.webui.SteamMsgCommon.StoreItem.getDefaultInstance() : storeItem_;
        }
      }
      /**
       * <code>optional .webui.StoreItem store_item = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.nickbooher.protos.webui.SteamMsgCommon.StoreItem, com.nickbooher.protos.webui.SteamMsgCommon.StoreItem.Builder, com.nickbooher.protos.webui.SteamMsgCommon.StoreItemOrBuilder> 
          getStoreItemFieldBuilder() {
        if (storeItemBuilder_ == null) {
          storeItemBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.nickbooher.protos.webui.SteamMsgCommon.StoreItem, com.nickbooher.protos.webui.SteamMsgCommon.StoreItem.Builder, com.nickbooher.protos.webui.SteamMsgCommon.StoreItemOrBuilder>(
                  getStoreItem(),
                  getParentForChildren(),
                  isClean());
          storeItem_ = null;
        }
        return storeItemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem)
    }

    // @@protoc_insertion_point(class_scope:webui.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem)
    private static final com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem();
    }

    public static com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CWishlist_GetWishlistItemsOnSale_Response_WishlistItem>
        PARSER = new com.google.protobuf.AbstractParser<CWishlist_GetWishlistItemsOnSale_Response_WishlistItem>() {
      @java.lang.Override
      public CWishlist_GetWishlistItemsOnSale_Response_WishlistItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CWishlist_GetWishlistItemsOnSale_Response_WishlistItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CWishlist_GetWishlistItemsOnSale_Response_WishlistItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgWishlist.CWishlist_GetWishlistItemsOnSale_Response_WishlistItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webui_CWishlist_GetWishlistItemsOnSale_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webui_CWishlist_GetWishlistItemsOnSale_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_WishlistItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_WishlistItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026service_wishlist.proto\022\005webui\032\014common." +
      "proto\"\217\001\n(CWishlist_GetWishlistItemsOnSa" +
      "le_Request\022*\n\007context\030\001 \001(\0132\031.webui.Stor" +
      "eBrowseContext\0227\n\014data_request\030\002 \001(\0132!.w" +
      "ebui.StoreBrowseItemDataRequest\"y\n)CWish" +
      "list_GetWishlistItemsOnSale_Response\022L\n\005" +
      "items\030\001 \003(\0132=.webui.CWishlist_GetWishlis" +
      "tItemsOnSale_Response_WishlistItem\"m\n6CW" +
      "ishlist_GetWishlistItemsOnSale_Response_" +
      "WishlistItem\022\r\n\005appid\030\001 \001(\r\022$\n\nstore_ite" +
      "m\030\002 \001(\0132\020.webui.StoreItem2\207\001\n\010Wishlist\022{" +
      "\n\026GetWishlistItemsOnSale\022/.webui.CWishli" +
      "st_GetWishlistItemsOnSale_Request\0320.webu" +
      "i.CWishlist_GetWishlistItemsOnSale_Respo" +
      "nseB/\n\033com.nickbooher.protos.webuiB\020Stea" +
      "mMsgWishlist"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.nickbooher.protos.webui.SteamMsgCommon.getDescriptor(),
        });
    internal_static_webui_CWishlist_GetWishlistItemsOnSale_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webui_CWishlist_GetWishlistItemsOnSale_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webui_CWishlist_GetWishlistItemsOnSale_Request_descriptor,
        new java.lang.String[] { "Context", "DataRequest", });
    internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_WishlistItem_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_WishlistItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webui_CWishlist_GetWishlistItemsOnSale_Response_WishlistItem_descriptor,
        new java.lang.String[] { "Appid", "StoreItem", });
    descriptor.resolveAllFeaturesImmutable();
    com.nickbooher.protos.webui.SteamMsgCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
