// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service_physicalgoods.proto
// Protobuf Java Version: 4.28.2

package com.nickbooher.protos.webui;

public final class SteamMsgPhysicalGoods {
  private SteamMsgPhysicalGoods() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      SteamMsgPhysicalGoods.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CPhysicalGoods_CheckInventoryAvailableByPackage_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 packageid = 1;</code>
     * @return Whether the packageid field is set.
     */
    boolean hasPackageid();
    /**
     * <code>optional int32 packageid = 1;</code>
     * @return The packageid.
     */
    int getPackageid();

    /**
     * <code>optional string country_code = 2;</code>
     * @return Whether the countryCode field is set.
     */
    boolean hasCountryCode();
    /**
     * <code>optional string country_code = 2;</code>
     * @return The countryCode.
     */
    java.lang.String getCountryCode();
    /**
     * <code>optional string country_code = 2;</code>
     * @return The bytes for countryCode.
     */
    com.google.protobuf.ByteString
        getCountryCodeBytes();
  }
  /**
   * Protobuf type {@code webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Request}
   */
  public static final class CPhysicalGoods_CheckInventoryAvailableByPackage_Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Request)
      CPhysicalGoods_CheckInventoryAvailableByPackage_RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CPhysicalGoods_CheckInventoryAvailableByPackage_Request.class.getName());
    }
    // Use CPhysicalGoods_CheckInventoryAvailableByPackage_Request.newBuilder() to construct.
    private CPhysicalGoods_CheckInventoryAvailableByPackage_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CPhysicalGoods_CheckInventoryAvailableByPackage_Request() {
      countryCode_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request.class, com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request.Builder.class);
    }

    private int bitField0_;
    public static final int PACKAGEID_FIELD_NUMBER = 1;
    private int packageid_ = 0;
    /**
     * <code>optional int32 packageid = 1;</code>
     * @return Whether the packageid field is set.
     */
    @java.lang.Override
    public boolean hasPackageid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 packageid = 1;</code>
     * @return The packageid.
     */
    @java.lang.Override
    public int getPackageid() {
      return packageid_;
    }

    public static final int COUNTRY_CODE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object countryCode_ = "";
    /**
     * <code>optional string country_code = 2;</code>
     * @return Whether the countryCode field is set.
     */
    @java.lang.Override
    public boolean hasCountryCode() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string country_code = 2;</code>
     * @return The countryCode.
     */
    @java.lang.Override
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          countryCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string country_code = 2;</code>
     * @return The bytes for countryCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, packageid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, countryCode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, packageid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, countryCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request other = (com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request) obj;

      if (hasPackageid() != other.hasPackageid()) return false;
      if (hasPackageid()) {
        if (getPackageid()
            != other.getPackageid()) return false;
      }
      if (hasCountryCode() != other.hasCountryCode()) return false;
      if (hasCountryCode()) {
        if (!getCountryCode()
            .equals(other.getCountryCode())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPackageid()) {
        hash = (37 * hash) + PACKAGEID_FIELD_NUMBER;
        hash = (53 * hash) + getPackageid();
      }
      if (hasCountryCode()) {
        hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCountryCode().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Request)
        com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request.class, com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request.Builder.class);
      }

      // Construct using com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        packageid_ = 0;
        countryCode_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Request_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request getDefaultInstanceForType() {
        return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request build() {
        com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request buildPartial() {
        com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request result = new com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.packageid_ = packageid_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.countryCode_ = countryCode_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request) {
          return mergeFrom((com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request other) {
        if (other == com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request.getDefaultInstance()) return this;
        if (other.hasPackageid()) {
          setPackageid(other.getPackageid());
        }
        if (other.hasCountryCode()) {
          countryCode_ = other.countryCode_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                packageid_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                countryCode_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int packageid_ ;
      /**
       * <code>optional int32 packageid = 1;</code>
       * @return Whether the packageid field is set.
       */
      @java.lang.Override
      public boolean hasPackageid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 packageid = 1;</code>
       * @return The packageid.
       */
      @java.lang.Override
      public int getPackageid() {
        return packageid_;
      }
      /**
       * <code>optional int32 packageid = 1;</code>
       * @param value The packageid to set.
       * @return This builder for chaining.
       */
      public Builder setPackageid(int value) {

        packageid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 packageid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packageid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object countryCode_ = "";
      /**
       * <code>optional string country_code = 2;</code>
       * @return Whether the countryCode field is set.
       */
      public boolean hasCountryCode() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string country_code = 2;</code>
       * @return The countryCode.
       */
      public java.lang.String getCountryCode() {
        java.lang.Object ref = countryCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            countryCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string country_code = 2;</code>
       * @return The bytes for countryCode.
       */
      public com.google.protobuf.ByteString
          getCountryCodeBytes() {
        java.lang.Object ref = countryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string country_code = 2;</code>
       * @param value The countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        countryCode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string country_code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryCode() {
        countryCode_ = getDefaultInstance().getCountryCode();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string country_code = 2;</code>
       * @param value The bytes for countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        countryCode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Request)
    }

    // @@protoc_insertion_point(class_scope:webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Request)
    private static final com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request();
    }

    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CPhysicalGoods_CheckInventoryAvailableByPackage_Request>
        PARSER = new com.google.protobuf.AbstractParser<CPhysicalGoods_CheckInventoryAvailableByPackage_Request>() {
      @java.lang.Override
      public CPhysicalGoods_CheckInventoryAvailableByPackage_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CPhysicalGoods_CheckInventoryAvailableByPackage_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CPhysicalGoods_CheckInventoryAvailableByPackage_Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CPhysicalGoods_CheckInventoryAvailableByPackage_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool inventory_available = 1;</code>
     * @return Whether the inventoryAvailable field is set.
     */
    boolean hasInventoryAvailable();
    /**
     * <code>optional bool inventory_available = 1;</code>
     * @return The inventoryAvailable.
     */
    boolean getInventoryAvailable();

    /**
     * <code>optional bool high_pending_orders = 2;</code>
     * @return Whether the highPendingOrders field is set.
     */
    boolean hasHighPendingOrders();
    /**
     * <code>optional bool high_pending_orders = 2;</code>
     * @return The highPendingOrders.
     */
    boolean getHighPendingOrders();
  }
  /**
   * Protobuf type {@code webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Response}
   */
  public static final class CPhysicalGoods_CheckInventoryAvailableByPackage_Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Response)
      CPhysicalGoods_CheckInventoryAvailableByPackage_ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CPhysicalGoods_CheckInventoryAvailableByPackage_Response.class.getName());
    }
    // Use CPhysicalGoods_CheckInventoryAvailableByPackage_Response.newBuilder() to construct.
    private CPhysicalGoods_CheckInventoryAvailableByPackage_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CPhysicalGoods_CheckInventoryAvailableByPackage_Response() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response.class, com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response.Builder.class);
    }

    private int bitField0_;
    public static final int INVENTORY_AVAILABLE_FIELD_NUMBER = 1;
    private boolean inventoryAvailable_ = false;
    /**
     * <code>optional bool inventory_available = 1;</code>
     * @return Whether the inventoryAvailable field is set.
     */
    @java.lang.Override
    public boolean hasInventoryAvailable() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool inventory_available = 1;</code>
     * @return The inventoryAvailable.
     */
    @java.lang.Override
    public boolean getInventoryAvailable() {
      return inventoryAvailable_;
    }

    public static final int HIGH_PENDING_ORDERS_FIELD_NUMBER = 2;
    private boolean highPendingOrders_ = false;
    /**
     * <code>optional bool high_pending_orders = 2;</code>
     * @return Whether the highPendingOrders field is set.
     */
    @java.lang.Override
    public boolean hasHighPendingOrders() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bool high_pending_orders = 2;</code>
     * @return The highPendingOrders.
     */
    @java.lang.Override
    public boolean getHighPendingOrders() {
      return highPendingOrders_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, inventoryAvailable_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(2, highPendingOrders_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, inventoryAvailable_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, highPendingOrders_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response other = (com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response) obj;

      if (hasInventoryAvailable() != other.hasInventoryAvailable()) return false;
      if (hasInventoryAvailable()) {
        if (getInventoryAvailable()
            != other.getInventoryAvailable()) return false;
      }
      if (hasHighPendingOrders() != other.hasHighPendingOrders()) return false;
      if (hasHighPendingOrders()) {
        if (getHighPendingOrders()
            != other.getHighPendingOrders()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInventoryAvailable()) {
        hash = (37 * hash) + INVENTORY_AVAILABLE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getInventoryAvailable());
      }
      if (hasHighPendingOrders()) {
        hash = (37 * hash) + HIGH_PENDING_ORDERS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getHighPendingOrders());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Response)
        com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response.class, com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response.Builder.class);
      }

      // Construct using com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        inventoryAvailable_ = false;
        highPendingOrders_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Response_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response getDefaultInstanceForType() {
        return com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response build() {
        com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response buildPartial() {
        com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response result = new com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.inventoryAvailable_ = inventoryAvailable_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.highPendingOrders_ = highPendingOrders_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response) {
          return mergeFrom((com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response other) {
        if (other == com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response.getDefaultInstance()) return this;
        if (other.hasInventoryAvailable()) {
          setInventoryAvailable(other.getInventoryAvailable());
        }
        if (other.hasHighPendingOrders()) {
          setHighPendingOrders(other.getHighPendingOrders());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                inventoryAvailable_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                highPendingOrders_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean inventoryAvailable_ ;
      /**
       * <code>optional bool inventory_available = 1;</code>
       * @return Whether the inventoryAvailable field is set.
       */
      @java.lang.Override
      public boolean hasInventoryAvailable() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool inventory_available = 1;</code>
       * @return The inventoryAvailable.
       */
      @java.lang.Override
      public boolean getInventoryAvailable() {
        return inventoryAvailable_;
      }
      /**
       * <code>optional bool inventory_available = 1;</code>
       * @param value The inventoryAvailable to set.
       * @return This builder for chaining.
       */
      public Builder setInventoryAvailable(boolean value) {

        inventoryAvailable_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool inventory_available = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInventoryAvailable() {
        bitField0_ = (bitField0_ & ~0x00000001);
        inventoryAvailable_ = false;
        onChanged();
        return this;
      }

      private boolean highPendingOrders_ ;
      /**
       * <code>optional bool high_pending_orders = 2;</code>
       * @return Whether the highPendingOrders field is set.
       */
      @java.lang.Override
      public boolean hasHighPendingOrders() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bool high_pending_orders = 2;</code>
       * @return The highPendingOrders.
       */
      @java.lang.Override
      public boolean getHighPendingOrders() {
        return highPendingOrders_;
      }
      /**
       * <code>optional bool high_pending_orders = 2;</code>
       * @param value The highPendingOrders to set.
       * @return This builder for chaining.
       */
      public Builder setHighPendingOrders(boolean value) {

        highPendingOrders_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool high_pending_orders = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHighPendingOrders() {
        bitField0_ = (bitField0_ & ~0x00000002);
        highPendingOrders_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Response)
    }

    // @@protoc_insertion_point(class_scope:webui.CPhysicalGoods_CheckInventoryAvailableByPackage_Response)
    private static final com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response();
    }

    public static com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CPhysicalGoods_CheckInventoryAvailableByPackage_Response>
        PARSER = new com.google.protobuf.AbstractParser<CPhysicalGoods_CheckInventoryAvailableByPackage_Response>() {
      @java.lang.Override
      public CPhysicalGoods_CheckInventoryAvailableByPackage_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CPhysicalGoods_CheckInventoryAvailableByPackage_Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CPhysicalGoods_CheckInventoryAvailableByPackage_Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgPhysicalGoods.CPhysicalGoods_CheckInventoryAvailableByPackage_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033service_physicalgoods.proto\022\005webui\"b\n7" +
      "CPhysicalGoods_CheckInventoryAvailableBy" +
      "Package_Request\022\021\n\tpackageid\030\001 \001(\005\022\024\n\014co" +
      "untry_code\030\002 \001(\t\"t\n8CPhysicalGoods_Check" +
      "InventoryAvailableByPackage_Response\022\033\n\023" +
      "inventory_available\030\001 \001(\010\022\033\n\023high_pendin" +
      "g_orders\030\002 \001(\0102\265\001\n\rPhysicalGoods\022\243\001\n Che" +
      "ckInventoryAvailableByPackage\022>.webui.CP" +
      "hysicalGoods_CheckInventoryAvailableByPa" +
      "ckage_Request\032?.webui.CPhysicalGoods_Che" +
      "ckInventoryAvailableByPackage_ResponseB4" +
      "\n\033com.nickbooher.protos.webuiB\025SteamMsgP" +
      "hysicalGoods"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Request_descriptor,
        new java.lang.String[] { "Packageid", "CountryCode", });
    internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webui_CPhysicalGoods_CheckInventoryAvailableByPackage_Response_descriptor,
        new java.lang.String[] { "InventoryAvailable", "HighPendingOrders", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
