// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service_gamenotes.proto
// Protobuf Java Version: 4.28.2

package com.nickbooher.protos.webui;

public final class SteamMsgGameNotes {
  private SteamMsgGameNotes() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      SteamMsgGameNotes.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CGameNotes_UploadImage_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webui.CGameNotes_UploadImage_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string file_prefix = 1;</code>
     * @return Whether the filePrefix field is set.
     */
    boolean hasFilePrefix();
    /**
     * <code>optional string file_prefix = 1;</code>
     * @return The filePrefix.
     */
    java.lang.String getFilePrefix();
    /**
     * <code>optional string file_prefix = 1;</code>
     * @return The bytes for filePrefix.
     */
    com.google.protobuf.ByteString
        getFilePrefixBytes();

    /**
     * <code>optional string mime_type = 2;</code>
     * @return Whether the mimeType field is set.
     */
    boolean hasMimeType();
    /**
     * <code>optional string mime_type = 2;</code>
     * @return The mimeType.
     */
    java.lang.String getMimeType();
    /**
     * <code>optional string mime_type = 2;</code>
     * @return The bytes for mimeType.
     */
    com.google.protobuf.ByteString
        getMimeTypeBytes();

    /**
     * <code>optional bytes data = 3;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code webui.CGameNotes_UploadImage_Request}
   */
  public static final class CGameNotes_UploadImage_Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webui.CGameNotes_UploadImage_Request)
      CGameNotes_UploadImage_RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CGameNotes_UploadImage_Request.class.getName());
    }
    // Use CGameNotes_UploadImage_Request.newBuilder() to construct.
    private CGameNotes_UploadImage_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CGameNotes_UploadImage_Request() {
      filePrefix_ = "";
      mimeType_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.webui.SteamMsgGameNotes.internal_static_webui_CGameNotes_UploadImage_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.webui.SteamMsgGameNotes.internal_static_webui_CGameNotes_UploadImage_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request.class, com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request.Builder.class);
    }

    private int bitField0_;
    public static final int FILE_PREFIX_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object filePrefix_ = "";
    /**
     * <code>optional string file_prefix = 1;</code>
     * @return Whether the filePrefix field is set.
     */
    @java.lang.Override
    public boolean hasFilePrefix() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string file_prefix = 1;</code>
     * @return The filePrefix.
     */
    @java.lang.Override
    public java.lang.String getFilePrefix() {
      java.lang.Object ref = filePrefix_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filePrefix_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string file_prefix = 1;</code>
     * @return The bytes for filePrefix.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilePrefixBytes() {
      java.lang.Object ref = filePrefix_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MIME_TYPE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mimeType_ = "";
    /**
     * <code>optional string mime_type = 2;</code>
     * @return Whether the mimeType field is set.
     */
    @java.lang.Override
    public boolean hasMimeType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string mime_type = 2;</code>
     * @return The mimeType.
     */
    @java.lang.Override
    public java.lang.String getMimeType() {
      java.lang.Object ref = mimeType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mimeType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mime_type = 2;</code>
     * @return The bytes for mimeType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      java.lang.Object ref = mimeType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mimeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes data = 3;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, filePrefix_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, mimeType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, filePrefix_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, mimeType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request other = (com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request) obj;

      if (hasFilePrefix() != other.hasFilePrefix()) return false;
      if (hasFilePrefix()) {
        if (!getFilePrefix()
            .equals(other.getFilePrefix())) return false;
      }
      if (hasMimeType() != other.hasMimeType()) return false;
      if (hasMimeType()) {
        if (!getMimeType()
            .equals(other.getMimeType())) return false;
      }
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFilePrefix()) {
        hash = (37 * hash) + FILE_PREFIX_FIELD_NUMBER;
        hash = (53 * hash) + getFilePrefix().hashCode();
      }
      if (hasMimeType()) {
        hash = (37 * hash) + MIME_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMimeType().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webui.CGameNotes_UploadImage_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webui.CGameNotes_UploadImage_Request)
        com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.webui.SteamMsgGameNotes.internal_static_webui_CGameNotes_UploadImage_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.webui.SteamMsgGameNotes.internal_static_webui_CGameNotes_UploadImage_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request.class, com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request.Builder.class);
      }

      // Construct using com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        filePrefix_ = "";
        mimeType_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.webui.SteamMsgGameNotes.internal_static_webui_CGameNotes_UploadImage_Request_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request getDefaultInstanceForType() {
        return com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request build() {
        com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request buildPartial() {
        com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request result = new com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.filePrefix_ = filePrefix_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.mimeType_ = mimeType_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.data_ = data_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request) {
          return mergeFrom((com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request other) {
        if (other == com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request.getDefaultInstance()) return this;
        if (other.hasFilePrefix()) {
          filePrefix_ = other.filePrefix_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasMimeType()) {
          mimeType_ = other.mimeType_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                filePrefix_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                mimeType_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object filePrefix_ = "";
      /**
       * <code>optional string file_prefix = 1;</code>
       * @return Whether the filePrefix field is set.
       */
      public boolean hasFilePrefix() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string file_prefix = 1;</code>
       * @return The filePrefix.
       */
      public java.lang.String getFilePrefix() {
        java.lang.Object ref = filePrefix_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filePrefix_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string file_prefix = 1;</code>
       * @return The bytes for filePrefix.
       */
      public com.google.protobuf.ByteString
          getFilePrefixBytes() {
        java.lang.Object ref = filePrefix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filePrefix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string file_prefix = 1;</code>
       * @param value The filePrefix to set.
       * @return This builder for chaining.
       */
      public Builder setFilePrefix(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        filePrefix_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string file_prefix = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilePrefix() {
        filePrefix_ = getDefaultInstance().getFilePrefix();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string file_prefix = 1;</code>
       * @param value The bytes for filePrefix to set.
       * @return This builder for chaining.
       */
      public Builder setFilePrefixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        filePrefix_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object mimeType_ = "";
      /**
       * <code>optional string mime_type = 2;</code>
       * @return Whether the mimeType field is set.
       */
      public boolean hasMimeType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string mime_type = 2;</code>
       * @return The mimeType.
       */
      public java.lang.String getMimeType() {
        java.lang.Object ref = mimeType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mimeType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mime_type = 2;</code>
       * @return The bytes for mimeType.
       */
      public com.google.protobuf.ByteString
          getMimeTypeBytes() {
        java.lang.Object ref = mimeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mimeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mime_type = 2;</code>
       * @param value The mimeType to set.
       * @return This builder for chaining.
       */
      public Builder setMimeType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mimeType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mime_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMimeType() {
        mimeType_ = getDefaultInstance().getMimeType();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string mime_type = 2;</code>
       * @param value The bytes for mimeType to set.
       * @return This builder for chaining.
       */
      public Builder setMimeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        mimeType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 3;</code>
       * @return Whether the data field is set.
       */
      @java.lang.Override
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:webui.CGameNotes_UploadImage_Request)
    }

    // @@protoc_insertion_point(class_scope:webui.CGameNotes_UploadImage_Request)
    private static final com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request();
    }

    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CGameNotes_UploadImage_Request>
        PARSER = new com.google.protobuf.AbstractParser<CGameNotes_UploadImage_Request>() {
      @java.lang.Override
      public CGameNotes_UploadImage_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CGameNotes_UploadImage_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CGameNotes_UploadImage_Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CGameNotes_UploadImage_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webui.CGameNotes_UploadImage_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string filename = 1;</code>
     * @return Whether the filename field is set.
     */
    boolean hasFilename();
    /**
     * <code>optional string filename = 1;</code>
     * @return The filename.
     */
    java.lang.String getFilename();
    /**
     * <code>optional string filename = 1;</code>
     * @return The bytes for filename.
     */
    com.google.protobuf.ByteString
        getFilenameBytes();
  }
  /**
   * Protobuf type {@code webui.CGameNotes_UploadImage_Response}
   */
  public static final class CGameNotes_UploadImage_Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webui.CGameNotes_UploadImage_Response)
      CGameNotes_UploadImage_ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CGameNotes_UploadImage_Response.class.getName());
    }
    // Use CGameNotes_UploadImage_Response.newBuilder() to construct.
    private CGameNotes_UploadImage_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CGameNotes_UploadImage_Response() {
      filename_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.webui.SteamMsgGameNotes.internal_static_webui_CGameNotes_UploadImage_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.webui.SteamMsgGameNotes.internal_static_webui_CGameNotes_UploadImage_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response.class, com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response.Builder.class);
    }

    private int bitField0_;
    public static final int FILENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object filename_ = "";
    /**
     * <code>optional string filename = 1;</code>
     * @return Whether the filename field is set.
     */
    @java.lang.Override
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string filename = 1;</code>
     * @return The filename.
     */
    @java.lang.Override
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string filename = 1;</code>
     * @return The bytes for filename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, filename_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, filename_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response other = (com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response) obj;

      if (hasFilename() != other.hasFilename()) return false;
      if (hasFilename()) {
        if (!getFilename()
            .equals(other.getFilename())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFilename()) {
        hash = (37 * hash) + FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFilename().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webui.CGameNotes_UploadImage_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webui.CGameNotes_UploadImage_Response)
        com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.webui.SteamMsgGameNotes.internal_static_webui_CGameNotes_UploadImage_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.webui.SteamMsgGameNotes.internal_static_webui_CGameNotes_UploadImage_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response.class, com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response.Builder.class);
      }

      // Construct using com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        filename_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.webui.SteamMsgGameNotes.internal_static_webui_CGameNotes_UploadImage_Response_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response getDefaultInstanceForType() {
        return com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response build() {
        com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response buildPartial() {
        com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response result = new com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.filename_ = filename_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response) {
          return mergeFrom((com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response other) {
        if (other == com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response.getDefaultInstance()) return this;
        if (other.hasFilename()) {
          filename_ = other.filename_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                filename_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object filename_ = "";
      /**
       * <code>optional string filename = 1;</code>
       * @return Whether the filename field is set.
       */
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string filename = 1;</code>
       * @return The filename.
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filename_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string filename = 1;</code>
       * @return The bytes for filename.
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string filename = 1;</code>
       * @param value The filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        filename_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilename() {
        filename_ = getDefaultInstance().getFilename();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 1;</code>
       * @param value The bytes for filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        filename_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:webui.CGameNotes_UploadImage_Response)
    }

    // @@protoc_insertion_point(class_scope:webui.CGameNotes_UploadImage_Response)
    private static final com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response();
    }

    public static com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CGameNotes_UploadImage_Response>
        PARSER = new com.google.protobuf.AbstractParser<CGameNotes_UploadImage_Response>() {
      @java.lang.Override
      public CGameNotes_UploadImage_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CGameNotes_UploadImage_Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CGameNotes_UploadImage_Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.webui.SteamMsgGameNotes.CGameNotes_UploadImage_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webui_CGameNotes_UploadImage_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webui_CGameNotes_UploadImage_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webui_CGameNotes_UploadImage_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webui_CGameNotes_UploadImage_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027service_gamenotes.proto\022\005webui\"V\n\036CGam" +
      "eNotes_UploadImage_Request\022\023\n\013file_prefi" +
      "x\030\001 \001(\t\022\021\n\tmime_type\030\002 \001(\t\022\014\n\004data\030\003 \001(\014" +
      "\"3\n\037CGameNotes_UploadImage_Response\022\020\n\010f" +
      "ilename\030\001 \001(\t2i\n\tGameNotes\022\\\n\013UploadImag" +
      "e\022%.webui.CGameNotes_UploadImage_Request" +
      "\032&.webui.CGameNotes_UploadImage_Response" +
      "B0\n\033com.nickbooher.protos.webuiB\021SteamMs" +
      "gGameNotes"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_webui_CGameNotes_UploadImage_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webui_CGameNotes_UploadImage_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webui_CGameNotes_UploadImage_Request_descriptor,
        new java.lang.String[] { "FilePrefix", "MimeType", "Data", });
    internal_static_webui_CGameNotes_UploadImage_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_webui_CGameNotes_UploadImage_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webui_CGameNotes_UploadImage_Response_descriptor,
        new java.lang.String[] { "Filename", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
