// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: offline_ticket.proto
// Protobuf Java Version: 4.28.2

package com.nickbooher.protos.steam;

public final class OfflineTicket {
  private OfflineTicket() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      OfflineTicket.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Offline_TicketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:steam.Offline_Ticket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes encrypted_ticket = 1;</code>
     * @return Whether the encryptedTicket field is set.
     */
    boolean hasEncryptedTicket();
    /**
     * <code>optional bytes encrypted_ticket = 1;</code>
     * @return The encryptedTicket.
     */
    com.google.protobuf.ByteString getEncryptedTicket();

    /**
     * <code>optional bytes signature = 2;</code>
     * @return Whether the signature field is set.
     */
    boolean hasSignature();
    /**
     * <code>optional bytes signature = 2;</code>
     * @return The signature.
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>optional int32 kdf1 = 3;</code>
     * @return Whether the kdf1 field is set.
     */
    boolean hasKdf1();
    /**
     * <code>optional int32 kdf1 = 3;</code>
     * @return The kdf1.
     */
    int getKdf1();

    /**
     * <code>optional bytes salt1 = 4;</code>
     * @return Whether the salt1 field is set.
     */
    boolean hasSalt1();
    /**
     * <code>optional bytes salt1 = 4;</code>
     * @return The salt1.
     */
    com.google.protobuf.ByteString getSalt1();

    /**
     * <code>optional int32 kdf2 = 5;</code>
     * @return Whether the kdf2 field is set.
     */
    boolean hasKdf2();
    /**
     * <code>optional int32 kdf2 = 5;</code>
     * @return The kdf2.
     */
    int getKdf2();

    /**
     * <code>optional bytes salt2 = 6;</code>
     * @return Whether the salt2 field is set.
     */
    boolean hasSalt2();
    /**
     * <code>optional bytes salt2 = 6;</code>
     * @return The salt2.
     */
    com.google.protobuf.ByteString getSalt2();
  }
  /**
   * Protobuf type {@code steam.Offline_Ticket}
   */
  public static final class Offline_Ticket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:steam.Offline_Ticket)
      Offline_TicketOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Offline_Ticket.class.getName());
    }
    // Use Offline_Ticket.newBuilder() to construct.
    private Offline_Ticket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Offline_Ticket() {
      encryptedTicket_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      salt1_ = com.google.protobuf.ByteString.EMPTY;
      salt2_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nickbooher.protos.steam.OfflineTicket.internal_static_steam_Offline_Ticket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nickbooher.protos.steam.OfflineTicket.internal_static_steam_Offline_Ticket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket.class, com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket.Builder.class);
    }

    private int bitField0_;
    public static final int ENCRYPTED_TICKET_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encryptedTicket_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes encrypted_ticket = 1;</code>
     * @return Whether the encryptedTicket field is set.
     */
    @java.lang.Override
    public boolean hasEncryptedTicket() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes encrypted_ticket = 1;</code>
     * @return The encryptedTicket.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedTicket() {
      return encryptedTicket_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes signature = 2;</code>
     * @return Whether the signature field is set.
     */
    @java.lang.Override
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes signature = 2;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int KDF1_FIELD_NUMBER = 3;
    private int kdf1_ = 0;
    /**
     * <code>optional int32 kdf1 = 3;</code>
     * @return Whether the kdf1 field is set.
     */
    @java.lang.Override
    public boolean hasKdf1() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 kdf1 = 3;</code>
     * @return The kdf1.
     */
    @java.lang.Override
    public int getKdf1() {
      return kdf1_;
    }

    public static final int SALT1_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString salt1_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes salt1 = 4;</code>
     * @return Whether the salt1 field is set.
     */
    @java.lang.Override
    public boolean hasSalt1() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes salt1 = 4;</code>
     * @return The salt1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSalt1() {
      return salt1_;
    }

    public static final int KDF2_FIELD_NUMBER = 5;
    private int kdf2_ = 0;
    /**
     * <code>optional int32 kdf2 = 5;</code>
     * @return Whether the kdf2 field is set.
     */
    @java.lang.Override
    public boolean hasKdf2() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 kdf2 = 5;</code>
     * @return The kdf2.
     */
    @java.lang.Override
    public int getKdf2() {
      return kdf2_;
    }

    public static final int SALT2_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString salt2_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes salt2 = 6;</code>
     * @return Whether the salt2 field is set.
     */
    @java.lang.Override
    public boolean hasSalt2() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bytes salt2 = 6;</code>
     * @return The salt2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSalt2() {
      return salt2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, encryptedTicket_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, signature_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, kdf1_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, salt1_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, kdf2_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBytes(6, salt2_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, encryptedTicket_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, kdf1_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, salt1_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, kdf2_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, salt2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket)) {
        return super.equals(obj);
      }
      com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket other = (com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket) obj;

      if (hasEncryptedTicket() != other.hasEncryptedTicket()) return false;
      if (hasEncryptedTicket()) {
        if (!getEncryptedTicket()
            .equals(other.getEncryptedTicket())) return false;
      }
      if (hasSignature() != other.hasSignature()) return false;
      if (hasSignature()) {
        if (!getSignature()
            .equals(other.getSignature())) return false;
      }
      if (hasKdf1() != other.hasKdf1()) return false;
      if (hasKdf1()) {
        if (getKdf1()
            != other.getKdf1()) return false;
      }
      if (hasSalt1() != other.hasSalt1()) return false;
      if (hasSalt1()) {
        if (!getSalt1()
            .equals(other.getSalt1())) return false;
      }
      if (hasKdf2() != other.hasKdf2()) return false;
      if (hasKdf2()) {
        if (getKdf2()
            != other.getKdf2()) return false;
      }
      if (hasSalt2() != other.hasSalt2()) return false;
      if (hasSalt2()) {
        if (!getSalt2()
            .equals(other.getSalt2())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEncryptedTicket()) {
        hash = (37 * hash) + ENCRYPTED_TICKET_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptedTicket().hashCode();
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      if (hasKdf1()) {
        hash = (37 * hash) + KDF1_FIELD_NUMBER;
        hash = (53 * hash) + getKdf1();
      }
      if (hasSalt1()) {
        hash = (37 * hash) + SALT1_FIELD_NUMBER;
        hash = (53 * hash) + getSalt1().hashCode();
      }
      if (hasKdf2()) {
        hash = (37 * hash) + KDF2_FIELD_NUMBER;
        hash = (53 * hash) + getKdf2();
      }
      if (hasSalt2()) {
        hash = (37 * hash) + SALT2_FIELD_NUMBER;
        hash = (53 * hash) + getSalt2().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code steam.Offline_Ticket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:steam.Offline_Ticket)
        com.nickbooher.protos.steam.OfflineTicket.Offline_TicketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nickbooher.protos.steam.OfflineTicket.internal_static_steam_Offline_Ticket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nickbooher.protos.steam.OfflineTicket.internal_static_steam_Offline_Ticket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket.class, com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket.Builder.class);
      }

      // Construct using com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        encryptedTicket_ = com.google.protobuf.ByteString.EMPTY;
        signature_ = com.google.protobuf.ByteString.EMPTY;
        kdf1_ = 0;
        salt1_ = com.google.protobuf.ByteString.EMPTY;
        kdf2_ = 0;
        salt2_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nickbooher.protos.steam.OfflineTicket.internal_static_steam_Offline_Ticket_descriptor;
      }

      @java.lang.Override
      public com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket getDefaultInstanceForType() {
        return com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket.getDefaultInstance();
      }

      @java.lang.Override
      public com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket build() {
        com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket buildPartial() {
        com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket result = new com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.encryptedTicket_ = encryptedTicket_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.signature_ = signature_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.kdf1_ = kdf1_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.salt1_ = salt1_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.kdf2_ = kdf2_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.salt2_ = salt2_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket) {
          return mergeFrom((com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket other) {
        if (other == com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket.getDefaultInstance()) return this;
        if (other.hasEncryptedTicket()) {
          setEncryptedTicket(other.getEncryptedTicket());
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        if (other.hasKdf1()) {
          setKdf1(other.getKdf1());
        }
        if (other.hasSalt1()) {
          setSalt1(other.getSalt1());
        }
        if (other.hasKdf2()) {
          setKdf2(other.getKdf2());
        }
        if (other.hasSalt2()) {
          setSalt2(other.getSalt2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                encryptedTicket_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                signature_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                kdf1_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                salt1_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                kdf2_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                salt2_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString encryptedTicket_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes encrypted_ticket = 1;</code>
       * @return Whether the encryptedTicket field is set.
       */
      @java.lang.Override
      public boolean hasEncryptedTicket() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes encrypted_ticket = 1;</code>
       * @return The encryptedTicket.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncryptedTicket() {
        return encryptedTicket_;
      }
      /**
       * <code>optional bytes encrypted_ticket = 1;</code>
       * @param value The encryptedTicket to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedTicket(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        encryptedTicket_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes encrypted_ticket = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptedTicket() {
        bitField0_ = (bitField0_ & ~0x00000001);
        encryptedTicket_ = getDefaultInstance().getEncryptedTicket();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signature = 2;</code>
       * @return Whether the signature field is set.
       */
      @java.lang.Override
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes signature = 2;</code>
       * @return The signature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>optional bytes signature = 2;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        signature_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signature = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private int kdf1_ ;
      /**
       * <code>optional int32 kdf1 = 3;</code>
       * @return Whether the kdf1 field is set.
       */
      @java.lang.Override
      public boolean hasKdf1() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 kdf1 = 3;</code>
       * @return The kdf1.
       */
      @java.lang.Override
      public int getKdf1() {
        return kdf1_;
      }
      /**
       * <code>optional int32 kdf1 = 3;</code>
       * @param value The kdf1 to set.
       * @return This builder for chaining.
       */
      public Builder setKdf1(int value) {

        kdf1_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 kdf1 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearKdf1() {
        bitField0_ = (bitField0_ & ~0x00000004);
        kdf1_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString salt1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes salt1 = 4;</code>
       * @return Whether the salt1 field is set.
       */
      @java.lang.Override
      public boolean hasSalt1() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes salt1 = 4;</code>
       * @return The salt1.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSalt1() {
        return salt1_;
      }
      /**
       * <code>optional bytes salt1 = 4;</code>
       * @param value The salt1 to set.
       * @return This builder for chaining.
       */
      public Builder setSalt1(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        salt1_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes salt1 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSalt1() {
        bitField0_ = (bitField0_ & ~0x00000008);
        salt1_ = getDefaultInstance().getSalt1();
        onChanged();
        return this;
      }

      private int kdf2_ ;
      /**
       * <code>optional int32 kdf2 = 5;</code>
       * @return Whether the kdf2 field is set.
       */
      @java.lang.Override
      public boolean hasKdf2() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 kdf2 = 5;</code>
       * @return The kdf2.
       */
      @java.lang.Override
      public int getKdf2() {
        return kdf2_;
      }
      /**
       * <code>optional int32 kdf2 = 5;</code>
       * @param value The kdf2 to set.
       * @return This builder for chaining.
       */
      public Builder setKdf2(int value) {

        kdf2_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 kdf2 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearKdf2() {
        bitField0_ = (bitField0_ & ~0x00000010);
        kdf2_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString salt2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes salt2 = 6;</code>
       * @return Whether the salt2 field is set.
       */
      @java.lang.Override
      public boolean hasSalt2() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bytes salt2 = 6;</code>
       * @return The salt2.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSalt2() {
        return salt2_;
      }
      /**
       * <code>optional bytes salt2 = 6;</code>
       * @param value The salt2 to set.
       * @return This builder for chaining.
       */
      public Builder setSalt2(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        salt2_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes salt2 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSalt2() {
        bitField0_ = (bitField0_ & ~0x00000020);
        salt2_ = getDefaultInstance().getSalt2();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:steam.Offline_Ticket)
    }

    // @@protoc_insertion_point(class_scope:steam.Offline_Ticket)
    private static final com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket();
    }

    public static com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Offline_Ticket>
        PARSER = new com.google.protobuf.AbstractParser<Offline_Ticket>() {
      @java.lang.Override
      public Offline_Ticket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Offline_Ticket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Offline_Ticket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nickbooher.protos.steam.OfflineTicket.Offline_Ticket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_steam_Offline_Ticket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_steam_Offline_Ticket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024offline_ticket.proto\022\005steam\"w\n\016Offline" +
      "_Ticket\022\030\n\020encrypted_ticket\030\001 \001(\014\022\021\n\tsig" +
      "nature\030\002 \001(\014\022\014\n\004kdf1\030\003 \001(\005\022\r\n\005salt1\030\004 \001(" +
      "\014\022\014\n\004kdf2\030\005 \001(\005\022\r\n\005salt2\030\006 \001(\014B,\n\033com.ni" +
      "ckbooher.protos.steamB\rOfflineTicket"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_steam_Offline_Ticket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_steam_Offline_Ticket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_steam_Offline_Ticket_descriptor,
        new java.lang.String[] { "EncryptedTicket", "Signature", "Kdf1", "Salt1", "Kdf2", "Salt2", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
