
package com.nickbooher.protos.webui.services;

import com.nickbooher.protos.webui.SteamMsgCommon;
import com.nickbooher.protos.webui.SteamMsgAuthentication;

public interface IAuthentication {

    public SteamMsgAuthentication.CAuthentication_BeginAuthSessionViaCredentials_Response BeginAuthSessionViaCredentials(SteamMsgAuthentication.CAuthentication_BeginAuthSessionViaCredentials_Request request);

    public SteamMsgAuthentication.CAuthentication_BeginAuthSessionViaQR_Response BeginAuthSessionViaQR(SteamMsgAuthentication.CAuthentication_BeginAuthSessionViaQR_Request request);

    public SteamMsgAuthentication.CAuthentication_RefreshToken_Enumerate_Response EnumerateTokens(SteamMsgAuthentication.CAuthentication_RefreshToken_Enumerate_Request request);

    public SteamMsgAuthentication.CAuthentication_AccessToken_GenerateForApp_Response GenerateAccessTokenForApp(SteamMsgAuthentication.CAuthentication_AccessToken_GenerateForApp_Request request);

    public SteamMsgAuthentication.CAuthentication_GetAuthSessionInfo_Response GetAuthSessionInfo(SteamMsgAuthentication.CAuthentication_GetAuthSessionInfo_Request request);

    public SteamMsgAuthentication.CAuthentication_GetAuthSessionRiskInfo_Response GetAuthSessionRiskInfo(SteamMsgAuthentication.CAuthentication_GetAuthSessionRiskInfo_Request request);

    public SteamMsgAuthentication.CAuthentication_GetAuthSessionsForAccount_Response GetAuthSessionsForAccount(SteamMsgAuthentication.CAuthentication_GetAuthSessionsForAccount_Request request);

    public SteamMsgAuthentication.CAuthentication_GetPasswordRSAPublicKey_Response GetPasswordRSAPublicKey(SteamMsgAuthentication.CAuthentication_GetPasswordRSAPublicKey_Request request);

    public SteamMsgAuthentication.CAuthentication_MigrateMobileSession_Response MigrateMobileSession(SteamMsgAuthentication.CAuthentication_MigrateMobileSession_Request request);

    public SteamMsgAuthentication.CAuthentication_PollAuthSessionStatus_Response PollAuthSessionStatus(SteamMsgAuthentication.CAuthentication_PollAuthSessionStatus_Request request);

    public SteamMsgAuthentication.CAuthentication_RefreshToken_Revoke_Response RevokeRefreshToken(SteamMsgAuthentication.CAuthentication_RefreshToken_Revoke_Request request);

    public SteamMsgAuthentication.CAuthentication_Token_Revoke_Response RevokeToken(SteamMsgAuthentication.CAuthentication_Token_Revoke_Request request);

    public SteamMsgAuthentication.CAuthentication_UpdateAuthSessionWithMobileConfirmation_Response UpdateAuthSessionWithMobileConfirmation(SteamMsgAuthentication.CAuthentication_UpdateAuthSessionWithMobileConfirmation_Request request);

    public SteamMsgAuthentication.CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response UpdateAuthSessionWithSteamGuardCode(SteamMsgAuthentication.CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request request);
    
}

