
package com.nickbooher.protos.webui.services;

import com.nickbooher.protos.webui.SteamMsgCommon;
import com.nickbooher.protos.webui.SteamMsgLoyaltyRewards;

public interface ILoyaltyRewards {

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_AddReaction_Response AddReaction(SteamMsgLoyaltyRewards.CLoyaltyRewards_AddReaction_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_BatchedQueryRewardItems_Response BatchedQueryRewardItems(SteamMsgLoyaltyRewards.CLoyaltyRewards_BatchedQueryRewardItems_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_GetActivePurchaseBonuses_Response GetActivePurchaseBonuses(SteamMsgLoyaltyRewards.CLoyaltyRewards_GetActivePurchaseBonuses_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_GetEligibleApps_Response GetEligibleApps(SteamMsgLoyaltyRewards.CLoyaltyRewards_GetEligibleApps_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_GetEquippedProfileItems_Response GetEquippedProfileItems(SteamMsgLoyaltyRewards.CLoyaltyRewards_GetEquippedProfileItems_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_GetPointsForSpend_Response GetPointsForSpend(SteamMsgLoyaltyRewards.CLoyaltyRewards_GetPointsForSpend_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_GetProfileCustomizationsConfig_Response GetProfileCustomizationsConfig(SteamMsgLoyaltyRewards.CLoyaltyRewards_GetProfileCustomizationsConfig_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_GetReactionConfig_Response GetReactionConfig(SteamMsgLoyaltyRewards.CLoyaltyRewards_GetReactionConfig_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_GetReactions_Response GetReactions(SteamMsgLoyaltyRewards.CLoyaltyRewards_GetReactions_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_GetReactionsSummaryForUser_Response GetReactionsSummaryForUser(SteamMsgLoyaltyRewards.CLoyaltyRewards_GetReactionsSummaryForUser_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_GetSummary_Response GetSummary(SteamMsgLoyaltyRewards.CLoyaltyRewards_GetSummary_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_QueryRewardItems_Response QueryRewardItems(SteamMsgLoyaltyRewards.CLoyaltyRewards_QueryRewardItems_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_RedeemPoints_Response RedeemPoints(SteamMsgLoyaltyRewards.CLoyaltyRewards_RedeemPoints_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_RedeemPoints_Response RedeemPointsForBadgeLevel(SteamMsgLoyaltyRewards.CLoyaltyRewards_RedeemPointsForBadgeLevel_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_RedeemPointsForProfileCustomization_Response RedeemPointsForProfileCustomization(SteamMsgLoyaltyRewards.CLoyaltyRewards_RedeemPointsForProfileCustomization_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_RedeemPointsForProfileCustomizationUpgrade_Response RedeemPointsForProfileCustomizationUpgrade(SteamMsgLoyaltyRewards.CLoyaltyRewards_RedeemPointsForProfileCustomizationUpgrade_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_RedeemPoints_Response RedeemPointsToUpgradeItem(SteamMsgLoyaltyRewards.CLoyaltyRewards_RedeemPointsToUpgradeItem_Request request);

    public SteamMsgLoyaltyRewards.CLoyaltyRewards_RegisterForSteamDeckRewards_Response RegisterForSteamDeckRewards(SteamMsgLoyaltyRewards.CLoyaltyRewards_RegisterForSteamDeckRewards_Request request);
    
}

