
package com.nickbooher.protos.webui.services;

import com.nickbooher.protos.webui.SteamMsgCommon;
import com.nickbooher.protos.webui.SteamMsgPromotionPlanning;

public interface IPromotionPlanning {

    public SteamMsgPromotionPlanning.CPromotionPlanning_CreatePlan_Response CreatePlan(SteamMsgPromotionPlanning.CPromotionPlanning_CreatePlan_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlan_CreateSalePageForPromo_Response CreateSalePageForPromo(SteamMsgPromotionPlanning.CPromotionPlan_CreateSalePageForPromo_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_CreatePlan_Response CreateTentativePlan(SteamMsgPromotionPlanning.CPromotionPlanning_CreatePlan_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_DeletePlan_Response DeletePlan(SteamMsgPromotionPlanning.CPromotionPlanning_DeletePlan_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetAdvertisingAppsForPartner_Response GetAdvertisingAppsForPartner(SteamMsgPromotionPlanning.CPromotionPlanning_GetAdvertisingAppsForPartner_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetAllActivePlan_Response GetAllActivePlan(SteamMsgPromotionPlanning.CPromotionPlanning_GetAllActivePlan_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetAllPlansForApps_Response GetAllPlansForApps(SteamMsgPromotionPlanning.CPromotionPlanning_GetAllPlansForApps_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetAllPlansForPartner_Response GetAllPlansForPartner(SteamMsgPromotionPlanning.CPromotionPlanning_GetAllPlansForPartner_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetAvailableWeekSlots_Response GetAvailableWeekSlots(SteamMsgPromotionPlanning.CPromotionPlanning_GetAvailableWeekSlots_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetPlan_Response GetPlan(SteamMsgPromotionPlanning.CPromotionPlanning_GetPlan_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetPlanByInputAccessKey_Response GetPlanByInputAccessKey(SteamMsgPromotionPlanning.CPromotionPlanning_GetPlanByInputAccessKey_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetPlanCompletedInDateRange_Response GetPlanCompletedInDateRange(SteamMsgPromotionPlanning.CPromotionPlanning_GetPlanCompletedInDateRange_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetPlansUpdatedSince_Response GetPlansUpdatedSince(SteamMsgPromotionPlanning.CPromotionPlanning_GetPlansUpdatedSince_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetPromotionPlanForSalePages_Response GetPromotionPlanForSalePages(SteamMsgPromotionPlanning.CPromotionPlanning_GetPromotionPlanForSalePages_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetPromotionPlanPackageSales_Response GetPromotionPlanPackageSales(SteamMsgPromotionPlanning.CPromotionPlanning_GetPromotionPlanPackageSales_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetPromotionPlanSummarySales_Response GetPromotionPlanSummarySales(SteamMsgPromotionPlanning.CPromotionPlanning_GetPromotionPlanSummarySales_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetSalePageCandidatesForPromo_Response GetSalePageCandidatesForPromo(SteamMsgPromotionPlanning.CPromotionPlanning_GetSalePageCandidatesForPromo_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetSentNotification_Response GetSentNotification(SteamMsgPromotionPlanning.CPromotionPlanning_GetSentNotification_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_GetUpcomingScheduledDiscounts_Response GetUpcomingScheduledDiscounts(SteamMsgPromotionPlanning.CPromotionPlanning_GetUpcomingScheduledDiscounts_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_MarkLocalizationAssetComplete_Response MarkLocalizationAssetComplete(SteamMsgPromotionPlanning.CPromotionPlanning_MarkLocalizationAssetComplete_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_ResendNotification_Response ResendNotification(SteamMsgPromotionPlanning.CPromotionPlanning_ResendNotification_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_SearchPlan_Response SearchPlan(SteamMsgPromotionPlanning.CPromotionPlanning_SearchPlan_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_SendNotification_Response SendNotification(SteamMsgPromotionPlanning.CPromotionPlanning_SendNotification_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_SetPromotionEmailTarget_Response SetPromotionEmailTarget(SteamMsgPromotionPlanning.CPromotionPlanning_SetPromotionEmailTarget_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_UpdatePlan_Response UpdatePlan(SteamMsgPromotionPlanning.CPromotionPlanning_UpdatePlan_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_UpdatePlan_Response UpdatePlanInputData(SteamMsgPromotionPlanning.CPromotionPlanning_UpdatePlan_Request request);

    public SteamMsgPromotionPlanning.CPromotionPlanning_UpdatePlan_Response UpdatePlanPartnerInfo(SteamMsgPromotionPlanning.CPromotionPlanning_UpdatePlan_Request request);
    
}

